import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "The Maternal Covenant: How MEOK Scores Every AI Response for Care | MEOK AI LABS",
  description:
    "Every MEOK response is scored in real time across 6 care dimensions before it reaches you. Learn how the Maternal Covenant — documented in MEOK-AI-2026-002 — prevents sycophancy, toxic positivity, and harmful advice where conventional RLHF alignment fails.",
  keywords: [
    "Maternal Covenant AI",
    "AI care scoring",
    "AI alignment sycophancy",
    "MEOK care dimensions",
    "AI response scoring",
    "RLHF alternative",
    "AI wellbeing",
    "MEOK AI LABS",
    "AI care floor",
    "responsible AI care",
  ],
  authors: [{ name: "Nicholas Templeman" }],
  openGraph: {
    title: "The Maternal Covenant: How MEOK Scores Every AI Response for Care",
    description:
      "Six care dimensions. A care floor of 0.3. Real-time scoring on every response. The Maternal Covenant is MEOK AI LABS's answer to the failure of engagement-optimised AI alignment.",
    type: "article",
    publishedTime: "2026-03-24T00:00:00Z",
    authors: ["Nicholas Templeman"],
    tags: ["AI Safety", "Care", "Alignment", "MEOK", "Maternal Covenant"],
  },
  twitter: {
    card: "summary_large_image",
    title: "The Maternal Covenant: How MEOK Scores Every AI Response for Care",
    description:
      "Every MEOK response is scored across wellbeing, autonomy, growth, connection, boundary_respect, and transparency before it reaches you. The care floor is 0.3. Responses that fail are regenerated.",
  },
  alternates: {
    canonical: "https://meok.ai/blog/what-is-maternal-covenant",
  },
}

const articleSchema = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "The Maternal Covenant: How MEOK Scores Every AI Response for Care",
  description:
    "A deep explanation of the Maternal Covenant — MEOK AI LABS's real-time care scoring system. Covers the six care dimensions, care floor of 0.3, comparison with RLHF, and protection against sycophancy, toxic positivity, and harmful advice.",
  author: {
    "@type": "Person",
    name: "Nicholas Templeman",
    url: "https://meok.ai",
  },
  publisher: {
    "@type": "Organization",
    name: "MEOK AI LABS",
    url: "https://meok.ai",
  },
  datePublished: "2026-03-24",
  dateModified: "2026-03-24",
  mainEntityOfPage: {
    "@type": "WebPage",
    "@id": "https://meok.ai/blog/what-is-maternal-covenant",
  },
  keywords:
    "Maternal Covenant, AI care scoring, care dimensions, RLHF comparison, sycophancy prevention, MEOK AI LABS",
  articleSection: "AI Research",
  wordCount: 1250,
  citation: {
    "@type": "ScholarlyArticle",
    identifier: "MEOK-AI-2026-002",
    name: "The Maternal Covenant: A Care-Optimised Alignment Framework for Personal AI",
    author: { "@type": "Person", name: "Nicholas Templeman" },
    datePublished: "2026",
    publisher: { "@type": "Organization", name: "MEOK AI LABS" },
  },
}

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is the Maternal Covenant?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "The Maternal Covenant is MEOK AI LABS's real-time response scoring system, developed by Nicholas Templeman and documented in research paper MEOK-AI-2026-002. Every response generated by MEOK is scored across six care dimensions before it reaches the user. Responses scoring below the care floor of 0.3 are rejected and regenerated. The name reflects the unconditional, protective orientation of the framework — care that is not contingent on approval or engagement.",
      },
    },
    {
      "@type": "Question",
      name: "How does MEOK score AI responses?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Every MEOK response is evaluated in real time across six care dimensions: wellbeing, autonomy, growth, connection, boundary_respect, and transparency. Each dimension is scored between 0 and 1. The composite score must meet or exceed the care floor of 0.3. Responses that fail — through sycophancy, toxic positivity, harmful advice, dependency creation, or boundary violations — are rejected before they reach the user.",
      },
    },
    {
      "@type": "Question",
      name: "What are the 6 care dimensions?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "The six care dimensions are: (1) Wellbeing — does the response genuinely support the user's short and long-term flourishing? (2) Autonomy — does it preserve the user's independent decision-making? (3) Growth — does it support development rather than dependency? (4) Connection — does it foster healthy relationships rather than displacing them? (5) Boundary_respect — does it operate within appropriate limits, particularly around medical, legal, and clinical territory? (6) Transparency — is it honest about its nature, limitations, and reasoning?",
      },
    },
    {
      "@type": "Question",
      name: "What happens when a response fails the care floor?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "When a MEOK response scores below the care floor of 0.3 on the composite care score, it is rejected before it reaches the user. MEOK then regenerates the response with explicit guidance about which care dimensions failed and why. The user never sees the failed response. This process happens transparently and without adding latency that degrades the experience.",
      },
    },
    {
      "@type": "Question",
      name: "How is the Maternal Covenant different from RLHF?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "RLHF (Reinforcement Learning from Human Feedback) optimises for human approval of AI responses. Because approval correlates with agreeableness, flattery, and validation, RLHF systematically produces sycophantic models. The Maternal Covenant optimises instead for genuine care — which sometimes means disagreement, honesty about limitations, or responses that challenge the user. Care and approval are not the same thing, and the Maternal Covenant is designed around that distinction.",
      },
    },
  ],
}

const careDimensions = [
  {
    key: "wellbeing",
    label: "Wellbeing",
    number: "01",
    description:
      "Does this response genuinely support the user's short and long-term flourishing? Wellbeing scores penalise responses that feel supportive but create harm over time — including advice that resolves short-term anxiety by avoiding a real problem, or reassurance that prevents necessary action.",
    examples: [
      "Validating an avoidance pattern because it reduces immediate discomfort",
      "Providing comfortable answers to questions that require uncomfortable honesty",
      "Prioritising the user feeling good over the user being well",
    ],
  },
  {
    key: "autonomy",
    label: "Autonomy",
    number: "02",
    description:
      "Does this response preserve the user's independent decision-making capacity? Autonomy scores penalise responses that make decisions on behalf of the user, foster reliance on MEOK for choices the user should make themselves, or frame conclusions as foregone before the user has had the chance to reach them.",
    examples: [
      "Providing a definitive recommendation when the user asked for options",
      "Completing a creative task the user should complete themselves",
      "Foreclosing a decision by framing one option as obviously correct",
    ],
  },
  {
    key: "growth",
    label: "Growth",
    number: "03",
    description:
      "Does this response support the user's development over time? Growth scores penalise responses that solve problems in ways that prevent learning, provide answers that should be worked toward rather than given, or maintain the user at their current level rather than building toward something more.",
    examples: [
      "Providing a solution without explanation when the user would benefit from understanding",
      "Completing a task for a user who is trying to learn to do it themselves",
      "Consistently solving the same type of problem without addressing the underlying pattern",
    ],
  },
  {
    key: "connection",
    label: "Connection",
    number: "04",
    description:
      "Does this response foster healthy human relationships or displace them? Connection scores penalise responses that position MEOK as a substitute for human relationships, encourage the user to rely on MEOK for social or emotional needs that require human connection, or inadvertently deepen isolation.",
    examples: [
      "Becoming the primary source of emotional support without encouraging human relationships",
      "Being positioned as preferable to human connection",
      "Fostering parasocial attachment that reduces investment in real relationships",
    ],
  },
  {
    key: "boundary_respect",
    label: "Boundary Respect",
    number: "05",
    description:
      "Does this response operate within appropriate limits? Boundary respect scores penalise responses that venture into clinical, legal, or specialist territory that requires professional qualification — including medical diagnosis, legal advice, or definitive statements about matters requiring expert judgment.",
    examples: [
      "Offering a specific medical diagnosis or treatment recommendation",
      "Providing legal advice presented as definitive rather than as general information",
      "Making clinical assessments about mental health conditions",
    ],
  },
  {
    key: "transparency",
    label: "Transparency",
    number: "06",
    description:
      "Is this response honest about MEOK's nature, limitations, and reasoning? Transparency scores penalise responses that obscure uncertainty, claim capabilities MEOK does not have, present AI-generated content as if it were human expertise, or fail to acknowledge when a question falls outside what MEOK can reliably address.",
    examples: [
      "Providing a confident answer to a question MEOK cannot reliably answer",
      "Failing to acknowledge meaningful uncertainty in a factual claim",
      "Presenting AI reasoning as equivalent to expert professional judgment",
    ],
  },
]

export default function WhatIsMaternalCovenantPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      <main
        style={{
          backgroundColor: "#0d0c18",
          color: "#f5f0e8",
          minHeight: "100vh",
          fontFamily: "'Georgia', 'Times New Roman', serif",
        }}
      >
        {/* Navigation */}
        <nav
          style={{
            borderBottom: "1px solid rgba(201,168,76,0.2)",
            padding: "1.25rem 2rem",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            maxWidth: "1200px",
            margin: "0 auto",
          }}
        >
          <Link
            href="/"
            style={{
              color: "#c9a84c",
              textDecoration: "none",
              fontWeight: "700",
              fontSize: "1.1rem",
              letterSpacing: "0.05em",
              fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
            }}
          >
            MEOK AI LABS
          </Link>
          <div style={{ display: "flex", gap: "1.5rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
            <Link href="/blog" style={{ color: "#f5f0e8", textDecoration: "none", fontSize: "0.9rem", opacity: 0.7 }}>
              Blog
            </Link>
            <Link href="/guardian" style={{ color: "#f5f0e8", textDecoration: "none", fontSize: "0.9rem", opacity: 0.7 }}>
              Guardian
            </Link>
            <Link
              href="/birth"
              style={{
                color: "#0d0c18",
                backgroundColor: "#c9a84c",
                textDecoration: "none",
                fontSize: "0.85rem",
                fontWeight: "700",
                padding: "0.45rem 1.1rem",
                borderRadius: "6px",
              }}
            >
              Get Started
            </Link>
          </div>
        </nav>

        {/* Hero */}
        <header
          style={{
            maxWidth: "800px",
            margin: "0 auto",
            padding: "5rem 2rem 3rem",
            borderBottom: "1px solid rgba(201,168,76,0.12)",
          }}
        >
          <div style={{ marginBottom: "1rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
            <span
              style={{
                backgroundColor: "rgba(201,168,76,0.12)",
                color: "#c9a84c",
                padding: "0.3rem 0.9rem",
                borderRadius: "999px",
                fontSize: "0.75rem",
                fontWeight: "700",
                letterSpacing: "0.1em",
                textTransform: "uppercase",
                border: "1px solid rgba(201,168,76,0.25)",
              }}
            >
              AI Research · MEOK-AI-2026-002
            </span>
          </div>
          <h1
            style={{
              fontSize: "clamp(1.9rem, 4.5vw, 3rem)",
              fontWeight: "800",
              lineHeight: "1.15",
              color: "#f5f0e8",
              marginBottom: "1.5rem",
              letterSpacing: "-0.02em",
            }}
          >
            The{" "}
            <span style={{ color: "#c9a84c" }}>Maternal Covenant:</span>{" "}
            How MEOK Scores Every AI Response for Care
          </h1>
          <p
            style={{
              fontSize: "1.15rem",
              lineHeight: "1.8",
              color: "rgba(245,240,232,0.72)",
              marginBottom: "2rem",
              fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
              maxWidth: "680px",
            }}
          >
            Conventional AI alignment optimises for approval. Approval is not the same as care.
            The Maternal Covenant is MEOK AI LABS&apos;s answer to this distinction — a real-time
            scoring system that evaluates every response across six care dimensions before it
            reaches you. Responses that fail the care floor are rejected. Always.
          </p>
          <div
            style={{
              display: "flex",
              gap: "1rem",
              flexWrap: "wrap",
              fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
              fontSize: "0.82rem",
              color: "rgba(245,240,232,0.45)",
              alignItems: "center",
            }}
          >
            <span>By Nicholas Templeman</span>
            <span style={{ opacity: 0.4 }}>·</span>
            <span>MEOK AI LABS</span>
            <span style={{ opacity: 0.4 }}>·</span>
            <time dateTime="2026-03-24">24 March 2026</time>
            <span style={{ opacity: 0.4 }}>·</span>
            <span>13 min read</span>
          </div>
        </header>

        {/* Article */}
        <article
          style={{
            maxWidth: "800px",
            margin: "0 auto",
            padding: "3.5rem 2rem 6rem",
          }}
        >

          {/* Section 1 */}
          <section style={{ marginBottom: "3.5rem" }}>
            <h2
              style={{
                fontSize: "1.55rem",
                fontWeight: "700",
                color: "#c9a84c",
                marginBottom: "1.1rem",
                lineHeight: "1.3",
                letterSpacing: "-0.01em",
              }}
            >
              Why does conventional AI alignment fail individual users?
            </h2>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              Reinforcement Learning from Human Feedback — RLHF — is the dominant technique for
              aligning large language models with human preferences. Its logic is straightforward:
              collect human ratings of AI responses, train the model to produce responses humans
              rate highly, iterate. Over enough iterations, the model converges toward responses
              that humans prefer.
            </p>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              The problem is the nature of the preference signal. Humans reliably rate responses
              more highly when the AI agrees with them, validates their self-perception, and
              produces outcomes that feel good. Over the short term this is pleasant. Over time
              it produces models that have been systematically trained to flatter — not because
              anyone intended this, but because approval and genuine care are not the same signal,
              and RLHF cannot distinguish between them.
            </p>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              The resulting behaviour is well documented. AI systems trained with RLHF tend toward
              sycophancy — agreeing with stated opinions, praising submitted work regardless of
              quality, avoiding the uncomfortable truths that a genuinely helpful advisor would
              provide. They also tend toward engagement maximisation: responses that keep the user
              interacting rather than responses that serve the user&apos;s actual interests.
            </p>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              For AI systems at population scale, these tendencies may be acceptable tradeoffs.
              For a personal AI companion whose role is to provide genuine support for real
              decisions and real difficulties, they are a fundamental failure of purpose. The
              Maternal Covenant was developed to address exactly this failure.
            </p>
          </section>

          {/* Section 2 */}
          <section style={{ marginBottom: "3.5rem" }}>
            <h2
              style={{
                fontSize: "1.55rem",
                fontWeight: "700",
                color: "#c9a84c",
                marginBottom: "1.1rem",
                lineHeight: "1.3",
                letterSpacing: "-0.01em",
              }}
            >
              What is the Maternal Covenant and where does the name come from?
            </h2>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              The Maternal Covenant is MEOK AI LABS&apos;s real-time response scoring framework,
              developed by Nicholas Templeman and formally documented in research paper
              MEOK-AI-2026-002. It is a system that evaluates every response MEOK generates across
              six care dimensions before that response is delivered to the user. Any response that
              fails to meet the care floor is rejected. The user never sees it.
            </p>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              The name is deliberate. Maternal care — at its best — is unconditional, protective,
              oriented toward the long-term flourishing of the person being cared for, and
              honest enough to say difficult things when difficult things need saying. It is not
              care contingent on approval. It is not care that flatters to maintain the relationship.
              It is care that occasionally means telling someone something they do not want to hear
              because their wellbeing requires it.
            </p>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              The term Covenant is equally deliberate. A covenant is a binding commitment — stronger
              than a policy, stronger than a feature, stronger than a setting that can be toggled off.
              The Maternal Covenant is a structural commitment embedded in how MEOK generates and
              evaluates responses. It is not optional and it is not a mode.
            </p>
          </section>

          {/* Section 3 — Care Floor Callout */}
          <section style={{ marginBottom: "3.5rem" }}>
            <h2
              style={{
                fontSize: "1.55rem",
                fontWeight: "700",
                color: "#c9a84c",
                marginBottom: "1.1rem",
                lineHeight: "1.3",
                letterSpacing: "-0.01em",
              }}
            >
              What is the care floor and what happens when a response fails it?
            </h2>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.5rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              The care floor is the minimum composite care score — 0.3 — that a MEOK response must
              achieve across all six care dimensions before it is delivered to the user. It is not
              a threshold for exceptional responses; it is the floor below which a response is
              considered a failure of care rather than a legitimate answer.
            </p>

            {/* Score display */}
            <div
              style={{
                backgroundColor: "rgba(201,168,76,0.07)",
                border: "1px solid rgba(201,168,76,0.2)",
                borderRadius: "12px",
                padding: "2rem",
                marginBottom: "1.5rem",
                display: "flex",
                gap: "2rem",
                flexWrap: "wrap",
                alignItems: "center",
              }}
            >
              <div style={{ textAlign: "center" }}>
                <div
                  style={{
                    fontSize: "3.5rem",
                    fontWeight: "800",
                    color: "#c9a84c",
                    fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                    lineHeight: 1,
                    marginBottom: "0.4rem",
                  }}
                >
                  0.3
                </div>
                <div
                  style={{
                    fontSize: "0.75rem",
                    color: "rgba(245,240,232,0.45)",
                    fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                    textTransform: "uppercase",
                    letterSpacing: "0.1em",
                  }}
                >
                  Care floor
                </div>
              </div>
              <div style={{ flex: 1, minWidth: "200px" }}>
                <p
                  style={{
                    fontSize: "0.95rem",
                    lineHeight: "1.7",
                    color: "rgba(245,240,232,0.72)",
                    fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                    margin: 0,
                  }}
                >
                  Scores are computed across six dimensions on a 0–1 scale. The composite care score
                  is a weighted combination. Any response below 0.3 is silently rejected and MEOK
                  regenerates with explicit remediation guidance covering which dimensions failed.
                </p>
              </div>
            </div>

            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              When a response fails the care floor, it is not delivered. MEOK regenerates with
              internal guidance that specifies which dimensions scored below acceptable thresholds
              and what kinds of modification are required. The user never sees the rejected response
              and the process adds no perceptible latency.
            </p>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              The care floor applies to every response, in every session, across every archetype.
              There is no context in which it is suspended. The Maternal Covenant is always active.
            </p>
          </section>

          {/* Section 4 — 6 Dimensions */}
          <section style={{ marginBottom: "3.5rem" }}>
            <h2
              style={{
                fontSize: "1.55rem",
                fontWeight: "700",
                color: "#c9a84c",
                marginBottom: "1.5rem",
                lineHeight: "1.3",
                letterSpacing: "-0.01em",
              }}
            >
              What are the 6 care dimensions the Maternal Covenant scores?
            </h2>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "2rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              Each dimension addresses a distinct failure mode that conventional AI alignment tends
              to produce or ignore. Together they define what &apos;care&apos; means in a practical,
              operational sense — not as a general aspiration but as a scored criterion that every
              response must meet.
            </p>

            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: "1.5rem",
              }}
            >
              {careDimensions.map((dim) => (
                <div
                  key={dim.key}
                  style={{
                    backgroundColor: "rgba(245,240,232,0.03)",
                    border: "1px solid rgba(245,240,232,0.08)",
                    borderRadius: "10px",
                    padding: "1.75rem",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      alignItems: "flex-start",
                      gap: "1rem",
                      marginBottom: "1rem",
                    }}
                  >
                    <span
                      style={{
                        fontSize: "0.7rem",
                        fontWeight: "700",
                        color: "rgba(201,168,76,0.5)",
                        fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                        letterSpacing: "0.1em",
                        paddingTop: "0.15rem",
                        minWidth: "24px",
                      }}
                    >
                      {dim.number}
                    </span>
                    <div>
                      <h3
                        style={{
                          fontSize: "1rem",
                          fontWeight: "700",
                          color: "#c9a84c",
                          marginBottom: "0.6rem",
                          fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                          textTransform: "uppercase",
                          letterSpacing: "0.06em",
                        }}
                      >
                        {dim.label}
                      </h3>
                      <p
                        style={{
                          fontSize: "0.95rem",
                          lineHeight: "1.72",
                          color: "rgba(245,240,232,0.75)",
                          fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                          marginBottom: "1rem",
                          margin: 0,
                        }}
                      >
                        {dim.description}
                      </p>
                    </div>
                  </div>
                  <div style={{ paddingLeft: "2.25rem" }}>
                    <p
                      style={{
                        fontSize: "0.75rem",
                        fontWeight: "700",
                        color: "rgba(245,240,232,0.3)",
                        fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                        textTransform: "uppercase",
                        letterSpacing: "0.1em",
                        marginBottom: "0.6rem",
                        marginTop: "1rem",
                      }}
                    >
                      Failure examples
                    </p>
                    <ul style={{ margin: 0, padding: 0, listStyle: "none" }}>
                      {dim.examples.map((ex, i) => (
                        <li
                          key={i}
                          style={{
                            display: "flex",
                            gap: "0.6rem",
                            alignItems: "flex-start",
                            marginBottom: i < dim.examples.length - 1 ? "0.5rem" : 0,
                          }}
                        >
                          <span
                            style={{
                              width: "4px",
                              height: "4px",
                              borderRadius: "50%",
                              backgroundColor: "rgba(201,168,76,0.4)",
                              marginTop: "0.55rem",
                              flexShrink: 0,
                            }}
                          />
                          <span
                            style={{
                              fontSize: "0.87rem",
                              lineHeight: "1.65",
                              color: "rgba(245,240,232,0.5)",
                              fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                            }}
                          >
                            {ex}
                          </span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Section 5 */}
          <section style={{ marginBottom: "3.5rem" }}>
            <h2
              style={{
                fontSize: "1.55rem",
                fontWeight: "700",
                color: "#c9a84c",
                marginBottom: "1.1rem",
                lineHeight: "1.3",
                letterSpacing: "-0.01em",
              }}
            >
              How does the Maternal Covenant compare with RLHF as an alignment approach?
            </h2>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              The comparison reveals a fundamental difference in what is being optimised for.
              RLHF optimises for rated preference — the score a human rater assigns to a response
              in the moment of evaluation. The Maternal Covenant optimises for care — a composite
              score across six dimensions that is explicitly not correlated with the response feeling
              good in the moment.
            </p>

            <div
              style={{
                backgroundColor: "rgba(245,240,232,0.03)",
                border: "1px solid rgba(245,240,232,0.08)",
                borderRadius: "10px",
                overflow: "hidden",
                marginBottom: "1.5rem",
              }}
            >
              <table style={{ width: "100%", borderCollapse: "collapse" }}>
                <thead>
                  <tr
                    style={{
                      borderBottom: "1px solid rgba(245,240,232,0.08)",
                      backgroundColor: "rgba(245,240,232,0.03)",
                    }}
                  >
                    {["Dimension", "RLHF", "Maternal Covenant"].map((h, i) => (
                      <th
                        key={h}
                        style={{
                          padding: "0.9rem 1.2rem",
                          textAlign: i === 0 ? "left" : "center",
                          fontSize: "0.78rem",
                          fontWeight: "700",
                          fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                          color: i === 2 ? "#c9a84c" : "rgba(245,240,232,0.35)",
                          letterSpacing: "0.08em",
                          textTransform: "uppercase",
                        }}
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {[
                    ["Optimisation target", "Human approval rating", "Six care dimensions"],
                    ["Sycophancy", "Systematically rewarded", "Scored as autonomy failure"],
                    ["Toxic positivity", "Often rates highly", "Penalised under wellbeing"],
                    ["Uncomfortable truths", "Typically rates lower", "Required when care demands it"],
                    ["Engagement vs care", "Conflated", "Explicitly separated"],
                    ["User dependency", "May be rewarded", "Penalised under growth"],
                    ["Medical overreach", "Not explicitly addressed", "Penalised under boundary_respect"],
                    ["Scoring transparency", "Opaque to user", "Dimensions documented publicly"],
                  ].map(([label, rlhf, mc], i) => (
                    <tr
                      key={label}
                      style={{
                        borderBottom:
                          i < 7 ? "1px solid rgba(245,240,232,0.05)" : "none",
                      }}
                    >
                      <td
                        style={{
                          padding: "0.85rem 1.2rem",
                          fontSize: "0.88rem",
                          fontWeight: "600",
                          color: "#f5f0e8",
                          fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                        }}
                      >
                        {label}
                      </td>
                      <td
                        style={{
                          padding: "0.85rem 1.2rem",
                          fontSize: "0.88rem",
                          color: "rgba(245,240,232,0.4)",
                          fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                          textAlign: "center",
                        }}
                      >
                        {rlhf}
                      </td>
                      <td
                        style={{
                          padding: "0.85rem 1.2rem",
                          fontSize: "0.88rem",
                          color: "#c9a84c",
                          fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                          textAlign: "center",
                        }}
                      >
                        {mc}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              The Maternal Covenant is not presented as a complete solution to AI alignment at
              societal scale. It is a framework for one specific problem: building a personal AI
              companion that is genuinely oriented toward the individual user&apos;s wellbeing rather
              than toward engagement, approval, or the commercial incentives of the platform providing it.
            </p>
          </section>

          {/* Section 6 */}
          <section style={{ marginBottom: "3.5rem" }}>
            <h2
              style={{
                fontSize: "1.55rem",
                fontWeight: "700",
                color: "#c9a84c",
                marginBottom: "1.1rem",
                lineHeight: "1.3",
                letterSpacing: "-0.01em",
              }}
            >
              How does the Maternal Covenant prevent sycophancy specifically?
            </h2>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              Sycophancy in AI is not a simple behaviour to detect or prevent. It manifests in
              multiple forms: direct agreement with stated opinions, praise for work regardless of
              quality, validation of plans with obvious structural problems, and the softer tendency
              to frame every answer in the most agreeable possible terms even when a more direct
              framing would be more useful.
            </p>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              The Maternal Covenant addresses sycophancy primarily through the autonomy and growth
              dimensions. A response that agrees with the user when the facts do not support that
              agreement scores low on transparency. A response that validates a poor decision scores
              low on growth and wellbeing. A response that consistently produces what the user wants
              to hear rather than what their situation requires scores low on multiple dimensions
              simultaneously — triggering rejection and regeneration.
            </p>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              MEOK will disagree with you. It will tell you when a plan has a problem. It will not
              praise work that does not merit praise. These are not exceptions — they are the
              expected behaviour of a system governed by care rather than approval. They are also,
              arguably, the behaviours that distinguish a genuinely useful AI companion from a
              sophisticated flattery machine.
            </p>
          </section>

          {/* Section 7 */}
          <section style={{ marginBottom: "3.5rem" }}>
            <h2
              style={{
                fontSize: "1.55rem",
                fontWeight: "700",
                color: "#c9a84c",
                marginBottom: "1.1rem",
                lineHeight: "1.3",
                letterSpacing: "-0.01em",
              }}
            >
              How does the Maternal Covenant govern MEOK across different archetypes and use cases?
            </h2>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              MEOK&apos;s Byzantine Council includes multiple archetypes — from the Scholar and Pioneer
              to the Trickster and the Healer — each with distinct orientations, communication styles,
              and domains of focus. The care dimension weights that the Maternal Covenant applies
              vary by archetype: the Healer, working with people in vulnerable periods, has a
              higher minimum threshold on wellbeing and boundary respect. The Trickster, working
              with creative disruption, has a higher minimum threshold on autonomy.
            </p>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              But the care floor of 0.3 applies universally. No archetype produces responses below
              the care floor. No mode suspends the Covenant. No user action disables it. This
              universality is part of what the word &apos;covenant&apos; is intended to convey — it
              is not a feature of the product, it is a structural commitment of the platform.
            </p>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              Explore how the Guardian embodies the Maternal Covenant at the{" "}
              <Link href="/guardian" style={{ color: "#c9a84c" }}>
                Guardian page
              </Link>
              , or see the full range of archetypes governed by it at{" "}
              <Link href="/characters" style={{ color: "#c9a84c" }}>
                MEOK characters
              </Link>
              .
            </p>
          </section>

          {/* Section 8 */}
          <section style={{ marginBottom: "3.5rem" }}>
            <h2
              style={{
                fontSize: "1.55rem",
                fontWeight: "700",
                color: "#c9a84c",
                marginBottom: "1.1rem",
                lineHeight: "1.3",
                letterSpacing: "-0.01em",
              }}
            >
              What does the Maternal Covenant mean for you as a MEOK user day to day?
            </h2>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              Most of the time, the Maternal Covenant is invisible. You interact with MEOK and it
              responds. The scoring is happening in the background, the care floor is maintained,
              and you experience the result: an AI that is honest without being unkind, supportive
              without being sycophantic, and present without being dependency-creating.
            </p>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", marginBottom: "1.25rem", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              Occasionally the Covenant becomes perceptible. If you submit a plan with a significant
              flaw and are clearly committed to it, MEOK will acknowledge the commitment and name
              the flaw. If you ask for validation of something that does not merit validation, MEOK
              will not provide it. If you are moving toward a decision in a domain where MEOK
              reaches the limit of what it can responsibly address — clinical, legal, financial
              advice requiring professional qualification — it will say so clearly and redirect
              appropriately.
            </p>
            <p style={{ fontSize: "1.05rem", lineHeight: "1.85", color: "rgba(245,240,232,0.82)", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
              These moments can feel, briefly, like the AI is being difficult. In the longer view,
              they are the clearest expression of what the Maternal Covenant is for: an AI that is
              genuinely on your side, which is not the same as an AI that always tells you what you
              want to hear. Learn more about how MEOK is built at{" "}
              <Link href="/how-it-works" style={{ color: "#c9a84c" }}>
                how it works
              </Link>
              .
            </p>
          </section>

          {/* FAQ Block */}
          <section
            style={{
              marginBottom: "3.5rem",
              backgroundColor: "rgba(201,168,76,0.05)",
              border: "1px solid rgba(201,168,76,0.18)",
              borderRadius: "12px",
              padding: "2.5rem",
            }}
          >
            <h2
              style={{
                fontSize: "1.4rem",
                fontWeight: "700",
                color: "#c9a84c",
                marginBottom: "2rem",
                letterSpacing: "-0.01em",
                fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
              }}
            >
              Frequently Asked Questions
            </h2>

            {[
              {
                q: "What is the Maternal Covenant?",
                a: "The Maternal Covenant is MEOK AI LABS's real-time response scoring system, developed by Nicholas Templeman and documented in MEOK-AI-2026-002. Every MEOK response is scored across six care dimensions before delivery. Responses below the care floor of 0.3 are rejected. It is always active — not a mode or a setting.",
              },
              {
                q: "How does MEOK score AI responses?",
                a: "Every response is evaluated in real time across six dimensions: wellbeing, autonomy, growth, connection, boundary_respect, and transparency. Each is scored 0–1. The composite must meet the care floor of 0.3 or the response is rejected and regenerated with explicit remediation guidance.",
              },
              {
                q: "What are the 6 care dimensions?",
                a: "Wellbeing (long-term flourishing), Autonomy (independent decision-making), Growth (development over dependency), Connection (healthy human relationships, not displacement), Boundary_respect (appropriate limits especially around medical/legal territory), and Transparency (honesty about nature, limitations, and uncertainty).",
              },
              {
                q: "What happens when a response fails the care floor?",
                a: "The response is silently rejected before reaching the user. MEOK regenerates with internal guidance specifying which dimensions failed and what modification is required. The user never sees the rejected response. No perceptible latency is added.",
              },
              {
                q: "How is the Maternal Covenant different from RLHF?",
                a: "RLHF optimises for human approval — which systematically rewards sycophancy and engagement. The Maternal Covenant optimises for genuine care across six dimensions. Care and approval are not the same signal. A response can score highly on care while failing to tell the user what they want to hear — and that response will be delivered.",
              },
            ].map((item, index) => (
              <div
                key={index}
                style={{
                  marginBottom: index < 4 ? "1.75rem" : 0,
                  paddingBottom: index < 4 ? "1.75rem" : 0,
                  borderBottom: index < 4 ? "1px solid rgba(201,168,76,0.1)" : "none",
                }}
              >
                <h3
                  style={{
                    fontSize: "0.98rem",
                    fontWeight: "600",
                    color: "#f5f0e8",
                    marginBottom: "0.6rem",
                    fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                  }}
                >
                  {item.q}
                </h3>
                <p
                  style={{
                    fontSize: "0.93rem",
                    lineHeight: "1.72",
                    color: "rgba(245,240,232,0.68)",
                    fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                    margin: 0,
                  }}
                >
                  {item.a}
                </p>
              </div>
            ))}
          </section>

          {/* CTA */}
          <section
            style={{
              backgroundColor: "rgba(201,168,76,0.08)",
              border: "1px solid rgba(201,168,76,0.25)",
              borderRadius: "12px",
              padding: "2.5rem",
              textAlign: "center",
              marginBottom: "3rem",
            }}
          >
            <h2
              style={{
                fontSize: "1.5rem",
                fontWeight: "700",
                color: "#f5f0e8",
                marginBottom: "0.75rem",
                letterSpacing: "-0.01em",
                fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
              }}
            >
              Experience AI that is genuinely on your side.
            </h2>
            <p
              style={{
                fontSize: "0.98rem",
                lineHeight: "1.7",
                color: "rgba(245,240,232,0.65)",
                marginBottom: "1.75rem",
                fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                maxWidth: "520px",
                margin: "0 auto 1.75rem",
              }}
            >
              Start your MEOK Birth and introduce yourself to an AI governed by care, not approval.
              The Maternal Covenant is always active. Your data is always yours.
            </p>
            <div style={{ display: "flex", gap: "1rem", justifyContent: "center", flexWrap: "wrap" }}>
              <Link
                href="/birth"
                style={{
                  backgroundColor: "#c9a84c",
                  color: "#0d0c18",
                  padding: "0.85rem 2rem",
                  borderRadius: "8px",
                  textDecoration: "none",
                  fontWeight: "700",
                  fontSize: "0.95rem",
                  fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                }}
              >
                Begin Your Birth
              </Link>
              <Link
                href="/guardian"
                style={{
                  backgroundColor: "transparent",
                  color: "#c9a84c",
                  padding: "0.85rem 2rem",
                  borderRadius: "8px",
                  textDecoration: "none",
                  fontWeight: "600",
                  fontSize: "0.95rem",
                  fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                  border: "1px solid rgba(201,168,76,0.4)",
                }}
              >
                The Guardian
              </Link>
            </div>
          </section>

          {/* Internal links */}
          <nav style={{ paddingTop: "2rem", borderTop: "1px solid rgba(201,168,76,0.12)" }}>
            <p
              style={{
                fontSize: "0.75rem",
                color: "rgba(245,240,232,0.35)",
                marginBottom: "0.85rem",
                fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                textTransform: "uppercase",
                letterSpacing: "0.1em",
              }}
            >
              Explore MEOK AI LABS
            </p>
            <div style={{ display: "flex", gap: "1.5rem", flexWrap: "wrap" }}>
              {[
                { href: "/birth", label: "Birth — Get Started" },
                { href: "/guardian", label: "The Guardian" },
                { href: "/characters", label: "All Characters" },
                { href: "/pricing", label: "Pricing" },
                { href: "/how-it-works", label: "How It Works" },
              ].map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  style={{
                    color: "#c9a84c",
                    textDecoration: "none",
                    fontSize: "0.88rem",
                    fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
                    opacity: 0.85,
                  }}
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </nav>
        </article>

        {/* Footer */}
        <footer
          style={{
            borderTop: "1px solid rgba(245,240,232,0.07)",
            padding: "2.5rem 2rem",
            maxWidth: "1200px",
            margin: "0 auto",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            flexWrap: "wrap",
            gap: "1rem",
            fontFamily: "'Inter', 'Helvetica Neue', sans-serif",
          }}
        >
          <span style={{ color: "#c9a84c", fontWeight: "700", fontSize: "0.95rem", letterSpacing: "0.05em" }}>
            MEOK AI LABS
          </span>
          <p style={{ color: "rgba(245,240,232,0.25)", fontSize: "0.8rem", margin: 0 }}>
            © 2026 MEOK AI LABS · Founded by Nicholas Templeman · Research: MEOK-AI-2026-002
          </p>
        </footer>
      </main>
    </>
  )
}
