/**
 * MEOK AI LABS — Chat & Profile Data Export
 *
 * GET /api/chat/export?format=json|markdown
 *
 * Returns the user's full data export (profile, companion config, OCEAN scores,
 * bond level, preferences). Supports JSON and Markdown formats.
 * Satisfies GDPR Article 20 (right to data portability).
 *
 * Auth: Clerk auth() — returns 401 if not authenticated.
 */

import { type NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { getUserById, getGuardianSettings } from '@/lib/db/user';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function GET(req: NextRequest) {
  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const format = req.nextUrl.searchParams.get('format') ?? 'json';
  if (format !== 'json' && format !== 'markdown') {
    return NextResponse.json(
      { error: 'Invalid format. Use "json" or "markdown".' },
      { status: 400 },
    );
  }

  // Gather user data
  const user = await getUserById(userId);
  if (!user) {
    return NextResponse.json({ error: 'User not found' }, { status: 404 });
  }

  const guardianSettings = await getGuardianSettings(userId);
  const exportedAt = new Date().toISOString();
  const dateSlug = exportedAt.split('T')[0];

  const exportData = {
    schema: 'MEOK Export Schema v1',
    exported_at: exportedAt,
    user_id: userId,
    profile: {
      email: user.email,
      name: user.name,
      tier: user.tier,
      created_at: user.created_at,
    },
    companion: {
      id: user.companion_id,
      name: user.companion_name,
      stage: user.companion_stage,
    },
    bond: {
      streak_days: user.streak_days,
      messages_total: user.messages_total,
      last_active_date: user.last_active_date,
    },
    // TODO: fetch OCEAN personality scores from personality/assessment table
    ocean_scores: null,
    preferences: {
      guardian_enabled: user.guardian_enabled,
      guardian_settings: guardianSettings ?? null,
    },
    // TODO: query messages table when schema is finalized
    // Example:
    //   const messages = await sql`SELECT id, role, content, created_at FROM messages WHERE user_id = ${userId} ORDER BY created_at ASC`;
    messages: [] as unknown[],
  };

  // ── JSON format ─────────────────────────────────────────────────────────────
  if (format === 'json') {
    const body = JSON.stringify(exportData, null, 2);
    return new NextResponse(body, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Content-Disposition': `attachment; filename="meok-export-${dateSlug}.json"`,
        'Cache-Control': 'no-store',
      },
    });
  }

  // ── Markdown format ─────────────────────────────────────────────────────────
  const md = [
    `# MEOK Data Export`,
    `**Exported:** ${exportedAt}`,
    `**User ID:** ${userId}`,
    '',
    '## Profile',
    `- **Name:** ${user.name ?? 'Not set'}`,
    `- **Email:** ${user.email}`,
    `- **Tier:** ${user.tier}`,
    `- **Member since:** ${user.created_at}`,
    '',
    '## Companion',
    `- **Character:** ${user.companion_id ?? 'None'}`,
    `- **Custom name:** ${user.companion_name ?? 'None'}`,
    `- **Stage:** ${user.companion_stage}`,
    '',
    '## Bond & Activity',
    `- **Streak:** ${user.streak_days} days`,
    `- **Total messages:** ${user.messages_total}`,
    `- **Last active:** ${user.last_active_date ?? 'Never'}`,
    '',
    '## Preferences',
    `- **Guardian enabled:** ${user.guardian_enabled ? 'Yes' : 'No'}`,
    '',
    '## Messages',
    '_Message export pending — full conversation history will be included in a future update._',
    '',
    '---',
    '_Generated by MEOK AI OS — GDPR Article 20 data portability export._',
  ].join('\n');

  return new NextResponse(md, {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Content-Disposition': `attachment; filename="meok-export-${dateSlug}.md"`,
      'Cache-Control': 'no-store',
    },
  });
}
