import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "EU AI Act Article 26 — Deployer Obligations + FRIA Implementation",
  description:
    "What Article 26 requires of deployers (not providers) of high-risk AI: instructions compliance, human oversight, monitoring, FRIA (26(9)) for public-sector and Annex III deployers. €15M / 3% fines.",
  alternates: { canonical: "https://meok.ai/eu-ai-act/article-26" },
};

const NAVY = "#1a1a2e";
const GOLD = "#c9a84c";
const BG = "#f5f0e8";

const FAQ = [
  { q: "Who is a 'deployer' under Article 26?", a: "A deployer is any natural or legal person, public authority, agency or other body using an AI system under their authority — except where the AI system is used in the course of a personal non-professional activity. If you put a high-risk AI into production, you're a deployer." },
  { q: "What's a Fundamental Rights Impact Assessment (FRIA)?", a: "Per Article 26(9), public-sector deployers + private deployers using AI for credit-worthiness, life/health insurance pricing must perform a FRIA prior to first use. The FRIA assesses risks to fundamental rights of natural persons that may arise from use of the AI. The EDPB published a harmonised DPIA template on 14 April 2026 that explicitly maps to FRIA inputs." },
  { q: "Is FRIA the same as a GDPR DPIA?", a: "Related but not identical. A GDPR Article 35 DPIA assesses risks to data-protection rights. A FRIA under Article 26(9) is broader — it covers all fundamental rights (freedom, equality, dignity, etc.) and is specific to AI systems. The EDPB harmonised template lets you fulfil both with one document." },
  { q: "When does the FRIA obligation kick in?", a: "Article 113 timeline: Article 26 obligations apply 24 months after entry into force = 2 August 2026. The Digital Omnibus delayed Annex III high-risk to 2 December 2027 for some categories, but FRIA obligations on listed deployers (banks, insurers, public bodies) apply from 2 Nov 2026." },
  { q: "How does MEOK cover Article 26 / FRIA?", a: "meok-dpia-edpb-template-mcp auto-fills the EDPB harmonised DPIA template — which IS the de-facto FRIA template since the EDPB explicitly designed it for AI Act use. /audit-prep-bundle (£4,950) wraps Article 26 + 26(9) FRIA in a 14-day engagement." },
];

const FAQ_JSONLD = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: FAQ.map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })) };

export default function Article26Page() {
  return (
    <main style={{ minHeight: "100vh", background: BG, color: NAVY }}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(FAQ_JSONLD) }} />
      <div style={{ maxWidth: 880, margin: "0 auto", padding: "5rem 1.5rem" }}>
        <Link href="/eu-ai-act" style={{ fontSize: 13, color: `${NAVY}66`, textDecoration: "none" }}>← All EU AI Act articles</Link>
        <h1 style={{ fontSize: "clamp(2.4rem, 5vw, 3.6rem)", fontWeight: 900, lineHeight: 1.05, letterSpacing: "-0.02em", marginTop: 24, marginBottom: 16 }}>EU AI Act Article 26 — Deployer Obligations + FRIA</h1>
        <p style={{ fontSize: "1.1rem", color: `${NAVY}99`, maxWidth: 720, marginBottom: 40, lineHeight: 1.6 }}>
          Most EU AI Act content focuses on AI providers. Article 26 is the parallel set of obligations for deployers — the companies actually using the AI in production. Banks, insurers, public bodies, and HR-tech buyers should read this most carefully.
        </p>

        <h2 style={{ fontSize: "1.5rem", fontWeight: 900, marginTop: 48, marginBottom: 16 }}>What Article 26 requires</h2>
        <ul style={{ paddingLeft: 20, color: `${NAVY}99`, lineHeight: 1.8, marginBottom: 32 }}>
          <li><strong>26(1)</strong> — Take appropriate technical + organisational measures to ensure use is in accordance with the provider's instructions for use.</li>
          <li><strong>26(2)</strong> — Assign human oversight to natural persons with the necessary competence, training, authority, and support.</li>
          <li><strong>26(3)</strong> — Ensure input data is relevant + sufficiently representative for the intended purpose where deployer exercises control.</li>
          <li><strong>26(4)</strong> — Monitor the operation based on instructions for use; inform the provider/distributor + stop use where there is reason to consider use is not in accordance.</li>
          <li><strong>26(5)</strong> — Retain logs automatically generated by the high-risk AI system for at least 6 months unless otherwise required by EU/national law.</li>
          <li><strong>26(6)</strong> — Inform workers' representatives + affected workers prior to deploying / using a high-risk AI system at the workplace.</li>
          <li><strong>26(7)</strong> — Public authority deployers must register the use in the EU public database for high-risk AI.</li>
          <li><strong>26(8)</strong> — Use information from the provider for own DPIA under GDPR Article 35.</li>
          <li><strong>26(9)</strong> — <strong>FRIA</strong>: public-sector deployers + private deployers in credit/insurance must perform a Fundamental Rights Impact Assessment prior to first use.</li>
          <li><strong>26(11)</strong> — Inform natural persons subject to AI-based decision-making in the cases listed in Annex III.</li>
        </ul>

        <h2 style={{ fontSize: "1.5rem", fontWeight: 900, marginTop: 48, marginBottom: 16 }}>How MEOK covers Article 26</h2>
        <div style={{ background: "white", borderRadius: 12, padding: 24, border: `1px solid ${NAVY}1a`, marginBottom: 32 }}>
          <ul style={{ paddingLeft: 20, color: `${NAVY}99`, lineHeight: 1.8 }}>
            <li><strong>meok-dpia-edpb-template-mcp</strong> — auto-fills the EDPB harmonised DPIA template (14 April 2026) which doubles as your FRIA per Article 26(9).</li>
            <li><strong>meok-governance-engine-mcp</strong> — Article 26 deployer-obligation crosswalk to ISO 42001 Annex A.7 + NIST AI RMF GOVERN.</li>
            <li><strong>/audit-prep-bundle (£4,950)</strong> — Article 26 + 26(9) FRIA in a 14-day signed engagement.</li>
          </ul>
        </div>

        <h2 style={{ fontSize: "1.5rem", fontWeight: 900, marginTop: 48, marginBottom: 20 }}>Frequently asked</h2>
        <div style={{ display: "grid", gap: 12, marginBottom: 32 }}>
          {FAQ.map((f) => (
            <details key={f.q} style={{ background: "white", borderRadius: 12, padding: "16px 20px", border: `1px solid ${NAVY}1a` }}>
              <summary style={{ fontWeight: 700, cursor: "pointer", fontSize: 15, color: NAVY }}>{f.q}</summary>
              <p style={{ marginTop: 10, color: `${NAVY}99`, fontSize: 14, lineHeight: 1.6 }}>{f.a}</p>
            </details>
          ))}
        </div>

        <div style={{ background: NAVY, color: "white", padding: 32, borderRadius: 16, textAlign: "center" }}>
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap", justifyContent: "center" }}>
            <Link href="/audit-prep-bundle" style={{ display: "inline-block", padding: "14px 24px", background: GOLD, color: NAVY, borderRadius: 12, fontWeight: 900, textDecoration: "none", fontSize: 14 }}>£4,950 Audit-Prep Bundle →</Link>
            <Link href="/scorecard" style={{ display: "inline-block", padding: "14px 24px", background: "transparent", color: "white", border: "1px solid rgba(255,255,255,0.3)", borderRadius: 12, fontWeight: 900, textDecoration: "none", fontSize: 14 }}>Free scorecard →</Link>
          </div>
        </div>

        <p style={{ marginTop: 40, color: `${NAVY}66`, fontSize: 12, textAlign: "center", lineHeight: 1.6 }}>
          Source: <a href="https://eur-lex.europa.eu/eli/reg/2024/1689/oj" style={{ color: GOLD }}>EU AI Act Regulation 2024/1689 Art. 26</a> · <a href="https://www.edpb.europa.eu/" style={{ color: GOLD }}>EDPB harmonised DPIA template (14 Apr 2026)</a> · MEOK AI Labs · CSOAI LTD · UK Companies House <strong>16939677</strong>
        </p>
      </div>
    </main>
  );
}
