/**
 * MEOK AI LABS — Companion Diary API
 *
 * GET /api/user/diary?limit=50&type=reflection&mood=reflective
 *
 * Returns companion diary entries from the diary_entries table.
 * These are generated by the chat pipeline every 25 messages and
 * represent the companion's introspective log of the relationship.
 */

import { NextRequest, NextResponse } from 'next/server';
import { requireAuth } from '@/lib/api-auth';
import { checkRateLimit } from '@/lib/rate-limit';
import { sql } from '@/lib/db';

export const runtime = 'nodejs';

export async function GET(req: NextRequest) {
  const authResult = await requireAuth();
  if (authResult.error) return authResult.error;
  const { userId } = authResult;

  const rateLimitResult = checkRateLimit(userId, 'explorer');
  if (!rateLimitResult.allowed) {
    return NextResponse.json({ error: 'Rate limit exceeded' }, { status: 429 });
  }

  const { searchParams } = new URL(req.url);
  const limit = Math.min(parseInt(searchParams.get('limit') ?? '50', 10), 200);
  const type = searchParams.get('type'); // 'reflection' | 'milestone' | 'care_action' | 'memory'
  const mood = searchParams.get('mood');

  if (!sql) {
    return NextResponse.json({ entries: [], source: 'db_unavailable' });
  }

  try {
    let rows;
    if (type && mood) {
      rows = await sql`
        SELECT id, companion_id, entry_type, content, topics, mood, bond_value, created_at
        FROM diary_entries
        WHERE user_id = ${userId}
          AND entry_type = ${type}
          AND mood = ${mood}
        ORDER BY created_at DESC
        LIMIT ${limit}
      `;
    } else if (type) {
      rows = await sql`
        SELECT id, companion_id, entry_type, content, topics, mood, bond_value, created_at
        FROM diary_entries
        WHERE user_id = ${userId}
          AND entry_type = ${type}
        ORDER BY created_at DESC
        LIMIT ${limit}
      `;
    } else if (mood) {
      rows = await sql`
        SELECT id, companion_id, entry_type, content, topics, mood, bond_value, created_at
        FROM diary_entries
        WHERE user_id = ${userId}
          AND mood = ${mood}
        ORDER BY created_at DESC
        LIMIT ${limit}
      `;
    } else {
      rows = await sql`
        SELECT id, companion_id, entry_type, content, topics, mood, bond_value, created_at
        FROM diary_entries
        WHERE user_id = ${userId}
        ORDER BY created_at DESC
        LIMIT ${limit}
      `;
    }

    return NextResponse.json({ entries: rows, total: rows.length });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    if (msg.includes('diary_entries') && msg.includes('does not exist')) {
      return NextResponse.json({ entries: [], source: 'table_pending_migration' });
    }
    console.error('[api/user/diary] GET error:', err);
    return NextResponse.json({ entries: [], source: 'error' });
  }
}
