"use client";

import { useState } from "react";
import Link from "next/link";
import {
  ArrowRight,
  PenLine,
  Code2,
  Palette,
  Mail,
  BookOpen,
  RefreshCw,
  CheckCircle2,
  Clock,
  Zap,
} from "lucide-react";

/* ─── JSON-LD ─────────────────────────────────────────── */

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Riri — The Builder Agent | MEOK AI LABS",
  description:
    "Riri is MEOK's overnight builder. She drafts content, writes code, builds assets, and delivers completed work to your dashboard before you wake up.",
  url: "https://meok.ai/work/riri",
  provider: { "@type": "Organization", name: "MEOK AI LABS", url: "https://meok.ai" },
};

/* ─── DATA ─────────────────────────────────────────────── */

const CAPABILITIES = [
  { emoji: "✍️", Icon: PenLine, title: "Content drafting", desc: "Blog posts, emails, social threads, press releases — drafted from your brief and ready for review." },
  { emoji: "💻", Icon: Code2, title: "Code generation", desc: "Functions, tests, documentation, bug fixes — written overnight in TypeScript, Python, and more." },
  { emoji: "🎨", Icon: Palette, title: "Creative assets", desc: "Copy variants, product descriptions, landing page sections — built to your spec while you sleep." },
  { emoji: "📧", Icon: Mail, title: "Email sequences", desc: "Nurture flows, outreach sequences, and follow-up campaigns drafted from your goals and voice." },
  { emoji: "📝", Icon: BookOpen, title: "Documentation", desc: "Technical docs, user guides, README files — Riri works through your documentation backlog overnight." },
  { emoji: "🔄", Icon: RefreshCw, title: "Refactoring tasks", desc: "Code cleanup, migration scripts, and dependency updates queued from your backlog and delivered for review." },
];

const WORK_QUEUE = [
  { id: "RR-001", type: "CODE", label: "Build /api/contacts POST endpoint", status: "complete", time: "2:14 AM", color: "text-cyan-400", bg: "bg-cyan-500/10 border-cyan-500/20" },
  { id: "RR-002", type: "CONTENT", label: "Write 3 LinkedIn posts — product launch", status: "complete", time: "3:05 AM", color: "text-emerald-400", bg: "bg-emerald-500/10 border-emerald-500/20" },
  { id: "RR-003", type: "DOCS", label: "Document Payments module API", status: "complete", time: "4:20 AM", color: "text-violet-400", bg: "bg-violet-500/10 border-violet-500/20" },
  { id: "RR-004", type: "CODE", label: "Write unit tests for auth.service.ts", status: "in-progress", time: "Now", color: "text-amber-400", bg: "bg-amber-500/10 border-amber-500/20" },
  { id: "RR-005", type: "CONTENT", label: "Draft investor update email", status: "queued", time: "Next", color: "text-white/30", bg: "bg-white/[0.04] border-white/10" },
];

const SAMPLE_OUTPUTS = [
  {
    label: "API Endpoint",
    lang: "TypeScript",
    color: "text-cyan-400",
    border: "border-cyan-500/20",
    bg: "bg-cyan-500/[0.03]",
    code: `// POST /api/contacts
// Generated by Riri · 2:14 AM

import { z } from "zod";
import { sql as db } from "@/lib/db";
import { contacts } from "@/db/schema";

const schema = z.object({
  name: z.string().min(1),
  email: z.string().email(),
  company: z.string().optional(),
  source: z.enum(["web", "import", "api"]),
});

export async function POST(req: Request) {
  const body = await req.json();
  const data = schema.parse(body);

  const [contact] = await db
    .insert(contacts)
    .values({ ...data, createdAt: new Date() })
    .returning();

  return Response.json({ contact }, { status: 201 });
}`,
  },
  {
    label: "Article Draft",
    lang: "Markdown",
    color: "text-emerald-400",
    border: "border-emerald-500/20",
    bg: "bg-emerald-500/[0.03]",
    code: `# Why Sovereign AI Is the Next Wave in Productivity

The promise of AI was always "work less, do more." But most tools still
require you to babysit the output. What if your AI actually ran while you
slept — and you woke up to completed work?

That's the bet MEOK is making with Work OS: three specialist agents
(Orion, Riri, Hourman) that execute autonomously overnight.

## The problem with co-pilots

Co-pilots help you write faster. Agents write for you. The distinction
sounds subtle — it isn't. A co-pilot waits for your input. An agent
acts on your intent.

When Riri runs overnight, there's no tab-switching, no prompting,
no "continue writing." You specify the output. Riri delivers it.

[Read more →]`,
  },
  {
    label: "Data Analysis",
    lang: "Python",
    color: "text-violet-400",
    border: "border-violet-500/20",
    bg: "bg-violet-500/[0.03]",
    code: `# Cohort retention analysis
# Generated by Riri · 3:47 AM

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("user_events.csv", parse_dates=["event_date"])

# Build cohort table
df["cohort"] = df.groupby("user_id")["event_date"].transform("min").dt.to_period("M")
df["period"] = df["event_date"].dt.to_period("M")
df["period_number"] = (df["period"] - df["cohort"]).apply(lambda x: x.n)

cohort_table = df.groupby(["cohort","period_number"])["user_id"].nunique().unstack()
retention = cohort_table.divide(cohort_table.iloc[:,0], axis=0)

print(retention.to_string())
# → M0: 100%  M1: 62%  M2: 48%  M3: 41%`,
  },
];

/* ─── PAGE ─────────────────────────────────────────────── */

export default function RiriPage() {
  const [buildInput, setBuildInput] = useState("");
  const [buildSubmitted, setBuildSubmitted] = useState(false);
  const [activeOutput, setActiveOutput] = useState(0);

  function handleBuild(e: React.FormEvent) {
    e.preventDefault();
    if (!buildInput.trim()) return;
    setBuildSubmitted(true);
  }

  return (
    <div className="min-h-screen bg-[#0d0c18] text-white overflow-x-hidden">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      {/* ─── HERO ─────────────────────────────────────────── */}
      <section className="relative pt-32 pb-28 px-6 text-center overflow-hidden">
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0"
          style={{ background: "radial-gradient(ellipse 80% 55% at 50% 0%, rgba(6,182,212,0.08) 0%, transparent 65%)" }}
        />
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 opacity-[0.03]"
          style={{
            backgroundImage: "linear-gradient(rgba(6,182,212,0.5) 1px, transparent 1px), linear-gradient(90deg, rgba(6,182,212,0.5) 1px, transparent 1px)",
            backgroundSize: "60px 60px",
          }}
        />

        <div className="relative max-w-4xl mx-auto">
          <Link href="/work" className="inline-flex items-center gap-2 text-xs font-semibold text-white/35 hover:text-cyan-400 transition-colors mb-10">
            ← Work OS
          </Link>

          <div className="block mb-6">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-cyan-400 text-[10px] font-black tracking-[0.2em] uppercase">
              <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse" />
              Agent 02 · Building now
            </div>
          </div>

          <div className="text-7xl sm:text-8xl mb-6">⚡</div>

          <h1 className="font-black text-white leading-[1.02] mb-4 text-5xl sm:text-7xl tracking-tight">
            Riri
          </h1>
          <p className="text-2xl sm:text-3xl font-black text-cyan-400 mb-6">The Builder</p>

          <p className="text-white/50 text-lg max-w-2xl mx-auto mb-10 leading-relaxed">
            Riri builds what you need and delivers completed work. Not a co-pilot. A builder. Spec it before bed. Wake up to finished output ready for review.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              href="/hatch"
              className="group inline-flex items-center gap-2 px-8 py-3.5 rounded-full font-black text-[#0d0c18] bg-[#c9a84c] hover:bg-[#d4b463] transition-all text-sm shadow-lg shadow-amber-900/20"
            >
              Put Riri to work tonight
              <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
            <Link href="/work" className="text-sm text-white/35 hover:text-white/60 transition-colors font-semibold">
              See all agents →
            </Link>
          </div>
        </div>
      </section>

      {/* ─── WHAT RIRI BUILDS ─────────────────────────────── */}
      <section className="py-24 px-6 bg-[#1a1a2e]">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <span className="text-xs font-black tracking-[0.25em] uppercase text-white/25 block mb-4">Capabilities</span>
            <h2 className="text-3xl sm:text-4xl font-black text-white leading-tight">
              What Riri builds while you sleep
            </h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {CAPABILITIES.map(({ emoji, title, desc }) => (
              <div key={title} className="rounded-2xl bg-[#0d0c18] border border-cyan-500/10 p-7 hover:border-cyan-500/25 transition-colors">
                <div className="text-3xl mb-4">{emoji}</div>
                <h3 className="font-black text-white text-base mb-3">{title}</h3>
                <p className="text-sm text-white/45 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── WORK QUEUE ───────────────────────────────────── */}
      <section className="py-24 px-6 bg-[#0d0c18]">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <span className="text-xs font-black tracking-[0.25em] uppercase text-white/25 block mb-4">Live Queue</span>
            <h2 className="text-3xl sm:text-4xl font-black text-white leading-tight">
              Riri&apos;s work queue — tonight
            </h2>
            <p className="text-white/40 text-base mt-4 max-w-xl mx-auto">
              Queue tasks before bed. Riri works through them in priority order. Everything is ready for your review by morning.
            </p>
          </div>

          <div className="rounded-3xl border border-cyan-500/15 bg-[#1a1a2e] overflow-hidden">
            {/* Queue header */}
            <div className="border-b border-cyan-500/10 px-6 py-4 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <Zap className="w-4 h-4 text-cyan-400" />
                <span className="text-sm font-black text-white">Riri Build Queue</span>
              </div>
              <div className="flex items-center gap-2 text-[10px] font-black tracking-[0.15em] uppercase text-cyan-400/60">
                <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse" />
                Running now
              </div>
            </div>

            {/* Queue items */}
            <div className="divide-y divide-white/[0.04]">
              {WORK_QUEUE.map((item) => (
                <div key={item.id} className="px-6 py-4 flex items-center gap-4">
                  <div className={`flex-shrink-0 px-2 py-0.5 rounded text-[9px] font-black tracking-wider uppercase border ${item.bg} ${item.color}`}>
                    {item.type}
                  </div>
                  <p className={`flex-1 text-sm font-semibold ${item.status === "queued" ? "text-white/30" : "text-white/70"}`}>
                    {item.label}
                  </p>
                  <div className="flex items-center gap-2 flex-shrink-0">
                    <span className="text-[10px] font-mono text-white/25">{item.time}</span>
                    {item.status === "complete" && <CheckCircle2 className="w-4 h-4 text-emerald-400" />}
                    {item.status === "in-progress" && (
                      <div className="flex items-center gap-1">
                        <div className="w-3 h-3 rounded-full border-2 border-cyan-400 border-t-transparent animate-spin" />
                      </div>
                    )}
                    {item.status === "queued" && <Clock className="w-4 h-4 text-white/20" />}
                  </div>
                </div>
              ))}
            </div>

            <div className="border-t border-cyan-500/10 px-6 py-4 bg-cyan-500/[0.03]">
              <p className="text-xs text-white/25 font-mono">
                Sample queue. Your actual queue is populated from your briefings and backlog.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ─── SAMPLE OUTPUTS ───────────────────────────────── */}
      <section className="py-24 px-6 bg-[#1a1a2e]">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <span className="text-xs font-black tracking-[0.25em] uppercase text-white/25 block mb-4">Sample output</span>
            <h2 className="text-3xl sm:text-4xl font-black text-white leading-tight">
              Real output from Riri
            </h2>
            <p className="text-white/40 text-base mt-4 max-w-xl mx-auto">
              Code, content, and analysis — all generated overnight, all ready for review.
            </p>
          </div>

          {/* Tab selector */}
          <div className="flex items-center gap-2 mb-6 overflow-x-auto pb-1">
            {SAMPLE_OUTPUTS.map((out, i) => (
              <button
                key={out.label}
                onClick={() => setActiveOutput(i)}
                className={`flex-shrink-0 px-4 py-2 rounded-full text-xs font-black tracking-wide transition-all ${
                  activeOutput === i
                    ? `${out.color} bg-white/10 border border-white/15`
                    : "text-white/35 hover:text-white/60 border border-transparent"
                }`}
              >
                {out.label}
              </button>
            ))}
          </div>

          {/* Code block */}
          {SAMPLE_OUTPUTS.map((out, i) => (
            <div
              key={out.label}
              className={`rounded-2xl border overflow-hidden transition-all ${out.border} ${out.bg} ${activeOutput === i ? "block" : "hidden"}`}
            >
              <div className={`flex items-center justify-between px-5 py-3 border-b ${out.border}`}>
                <div className="flex items-center gap-3">
                  <span className={`text-xs font-black tracking-[0.15em] uppercase ${out.color}`}>{out.label}</span>
                  <span className="text-[10px] text-white/30 font-mono">{out.lang}</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <div className="w-2.5 h-2.5 rounded-full bg-red-500/50" />
                  <div className="w-2.5 h-2.5 rounded-full bg-amber-500/50" />
                  <div className="w-2.5 h-2.5 rounded-full bg-emerald-500/50" />
                </div>
              </div>
              <pre className="p-5 sm:p-7 text-xs text-white/60 overflow-x-auto leading-relaxed font-mono whitespace-pre">
                {out.code}
              </pre>
            </div>
          ))}

          <p className="mt-4 text-xs text-white/25 font-mono text-center">
            Sample outputs. Your actual Riri output is based on your specific briefs and backlog.
          </p>
        </div>
      </section>

      {/* ─── WHAT SHOULD RIRI BUILD ───────────────────────── */}
      <section className="py-24 px-6 bg-[#0d0c18]">
        <div className="max-w-2xl mx-auto text-center">
          <div className="w-16 h-16 rounded-3xl bg-cyan-500/10 border border-cyan-500/25 flex items-center justify-center text-3xl mx-auto mb-8">
            ⚡
          </div>
          <h2 className="text-3xl sm:text-4xl font-black text-white mb-4 tracking-tight">
            What should Riri build?
          </h2>
          <p className="text-white/40 text-base mb-10 leading-relaxed">
            Describe what you need. Riri builds it overnight and delivers it to your dashboard by morning.
          </p>

          {!buildSubmitted ? (
            <form onSubmit={handleBuild} className="space-y-4">
              <textarea
                value={buildInput}
                onChange={(e) => setBuildInput(e.target.value)}
                placeholder={`e.g. "Write a POST /api/leads endpoint in TypeScript using Drizzle ORM. Validate with Zod. Add a Jest test."`}
                rows={4}
                className="w-full px-5 py-4 rounded-2xl bg-[#1a1a2e] border border-cyan-500/20 text-white placeholder-white/25 text-sm focus:outline-none focus:border-cyan-500/45 transition-colors resize-none leading-relaxed"
              />
              <div className="flex flex-col sm:flex-row items-center gap-3">
                <button
                  type="submit"
                  disabled={!buildInput.trim()}
                  className="group inline-flex items-center gap-2 px-8 py-3.5 rounded-full font-black text-[#0d0c18] bg-[#c9a84c] hover:bg-[#d4b463] disabled:opacity-40 disabled:cursor-not-allowed transition-all text-sm w-full sm:w-auto justify-center"
                >
                  <Zap className="w-4 h-4" />
                  Queue for tonight
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </button>
                <p className="text-xs text-white/25 font-mono">Requires Sovereign tier · £12/mo</p>
              </div>
            </form>
          ) : (
            <div className="rounded-2xl border border-emerald-500/25 bg-emerald-500/[0.06] p-8 text-center">
              <CheckCircle2 className="w-10 h-10 text-emerald-400 mx-auto mb-4" />
              <h3 className="font-black text-white text-lg mb-2">Added to Riri&apos;s queue.</h3>
              <p className="text-white/50 text-sm mb-6">Riri will build this tonight. Your output will be in your dashboard by 6am.</p>
              <Link href="/hatch" className="inline-flex items-center gap-2 px-6 py-3 rounded-full font-black text-[#0d0c18] bg-[#c9a84c] hover:bg-[#d4b463] transition-all text-sm">
                Activate full Riri access
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          )}
        </div>
      </section>

      {/* ─── GEO H2s ──────────────────────────────────────── */}
      <section className="py-24 px-6 bg-[#1a1a2e]">
        <div className="max-w-3xl mx-auto space-y-16">
          <div>
            <h2 className="text-2xl sm:text-3xl font-black text-white mb-5 leading-tight">What is Riri in MEOK AI?</h2>
            <p className="text-white/55 text-base leading-relaxed">
              Riri is MEOK&apos;s overnight creative and technical builder agent. She takes your task backlog and works through it during your sleep window — drafting content, writing code, building assets, and producing documentation. By morning, completed work is waiting in your brief for review. Riri handles the building; you handle the decisions.
            </p>
          </div>
          <div>
            <h2 className="text-2xl sm:text-3xl font-black text-white mb-5 leading-tight">Can Riri write production code?</h2>
            <p className="text-white/55 text-base leading-relaxed">
              Yes. Riri handles TypeScript, Python, and common web frameworks. She writes functions, tests, and documentation from your backlog — pulling tasks you&apos;ve queued and working through them autonomously. Results are delivered for human review, never committed autonomously. You stay in control of what ships.
            </p>
          </div>
          <div>
            <h2 className="text-2xl sm:text-3xl font-black text-white mb-5 leading-tight">Which tier unlocks Riri?</h2>
            <p className="text-white/55 text-base leading-relaxed">
              Riri is available on the Sovereign tier at £12/mo. All three agents — Orion, Riri, and Hourman — are included in a single subscription. No per-task fees. No add-ons. Everything you need to build overnight, every night.
            </p>
          </div>
        </div>
      </section>

      {/* ─── BOTTOM CTA ───────────────────────────────────── */}
      <section className="py-28 px-6 bg-[#0d0c18] text-center relative overflow-hidden">
        <div aria-hidden className="pointer-events-none absolute inset-0" style={{ background: "radial-gradient(ellipse 60% 50% at 50% 100%, rgba(201,168,76,0.08) 0%, transparent 70%)" }} />
        <div className="relative max-w-2xl mx-auto">
          <div className="flex items-center justify-center gap-3 mb-3">
            <Clock className="w-4 h-4 text-cyan-400/50" />
            <span className="text-xs font-black tracking-[0.2em] uppercase text-white/25">Other agents</span>
          </div>
          <p className="text-white/40 text-sm mb-8">Riri works alongside Orion and Hourman. All three share your sovereign memory.</p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
            <Link href="/work/orion" className="group inline-flex items-center gap-2 px-6 py-3 rounded-full font-black text-white border border-amber-500/25 hover:border-amber-500/50 bg-amber-500/[0.05] hover:bg-amber-500/[0.08] transition-all text-sm">
              🔭 Meet Orion <ArrowRight className="w-3.5 h-3.5" />
            </Link>
            <Link href="/work/hourman" className="group inline-flex items-center gap-2 px-6 py-3 rounded-full font-black text-white border border-violet-500/25 hover:border-violet-500/50 bg-violet-500/[0.05] hover:bg-violet-500/[0.08] transition-all text-sm">
              ⏱ Meet Hourman <ArrowRight className="w-3.5 h-3.5" />
            </Link>
            <Link href="/work/ralph" className="group inline-flex items-center gap-2 px-6 py-3 rounded-full font-black text-[#0d0c18] bg-[#c9a84c] hover:bg-[#d4b463] transition-all text-sm">
              🧠 Ralph Mode <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          </div>
        </div>
      </section>

    </div>
  );
}
