// Canonical list of CSOAI-ORG MCPs published to Anthropic Registry.
// Generated 2026-05-21 from registry.modelcontextprotocol.io.
// Refresh by running: scripts/refresh_registry_list.sh (see _template/scripts/).

export type RegistryMCP = {
  slug: string;
  version: string;
  category: "governance" | "a2a" | "trade" | "industry" | "cybersec" | "devtool" | "platform";
  title: string;
  description: string;
};

export const MCPS: RegistryMCP[] = [
  // ── Governance (11) ────────────────────────────────────────────
  { slug: "eu-ai-act-compliance-mcp", version: "1.5.1", category: "governance",
    title: "EU AI Act Compliance",
    description: "410 articles from EUR-Lex via FTS5 search, Annex III high-risk classifier, Article 50 transparency, Article 73 incident reporting, 42-point audit, penalty calculator." },
  { slug: "iso-42005-impact-mcp", version: "1.0.0", category: "governance",
    title: "ISO/IEC 42005:2025 AI Impact Assessment",
    description: "First international standard for AI impact assessment (May 2025). 6 lifecycle phases × 7 impact categories. Cross-walks to EU AI Act Articles + ISO 42001 clauses. Companion to ISO 42001 AIMS." },
  { slug: "korea-ai-basic-act-mcp", version: "1.0.0", category: "governance",
    title: "Korea AI Basic Act (NEW)",
    description: "Republic of Korea AI Basic Act — in force 22 January 2026. High-impact AI classification, mandatory GenAI labelling, MSIT obligations. Cross-walks to EU AI Act + Japan AI Promotion Act." },
  { slug: "dora-compliance-mcp", version: "1.2.9", category: "governance",
    title: "DORA Compliance",
    description: "EU Digital Operational Resilience Act 5-pillar audit, Article 28 Register of Information, TLPT readiness, incident classification." },
  { slug: "nis2-compliance-mcp", version: "1.2.9", category: "governance",
    title: "NIS2 Compliance",
    description: "NIS2 Directive Article 21 risk-management measures, Article 23 incident classification, Article 20 accountability for essential/important entities." },
  { slug: "cra-compliance-mcp", version: "1.2.6", category: "governance",
    title: "Cyber Resilience Act",
    description: "EU CRA Annex I classifier, SBOM generation, vulnerability handling, conformity assessment. Sept 2027 cliff." },
  { slug: "ai-bom-mcp", version: "1.2.7", category: "governance",
    title: "AI Bill of Materials",
    description: "CycloneDX ML-BOM 1.6 + SPDX 3.0 AI profile, EU AI Act Annex IV mapping, NIST AI RMF alignment." },
  { slug: "ai-incident-reporting-mcp", version: "1.0.2", category: "governance",
    title: "AI Incident Reporting",
    description: "Unified incident classification across EU AI Act Art 73, DORA Art 19, NIS2 Art 23, GDPR Art 33, ISO/IEC 42001 — one incident triggers all regime clocks." },
  { slug: "agent-incident-relay-mcp", version: "1.0.0", category: "governance",
    title: "Agent Incident Relay (NEW)",
    description: "Article 73 5-clock broadcaster: one incident → simultaneous signed reports to EU AI Act Art 73 + DORA Art 19 + NIS2 Art 23 + GDPR Art 33 + ISO 42001 cl 10.1. Single incident_id drives all 5 regimes from the same detection timestamp. Companion to ai-incident-reporting-mcp." },
  { slug: "meok-nis2-nl-register-mcp", version: "1.0.0", category: "governance",
    title: "NIS2 Netherlands (Wbni-2) Register (NEW)",
    description: "Wbni-2 (NL NIS2) registration packet generator. Classifies Annex I essential / Annex II important + size, generates NCSC-NL portal payload + Article 21 attestation. DEADLINE 30 June 2026. Post-deadline: €100K-€10M + director liability." },
  { slug: "meok-cra-art14-reporter-mcp", version: "1.0.0", category: "governance",
    title: "CRA Article 14 Reporter (NEW)",
    description: "EU Cyber Resilience Act Article 14 actively-exploited-vulnerability notifier. 24h/72h/14d three-clock tracker. Generates ENISA + national-CSIRT payload (DE BSI / FR ANSSI / NL NCSC-NL / 7 more). DEADLINE 11 September 2026 — every EU software vendor needs this." },
  { slug: "meok-c2pa-durable-mcp", version: "1.0.0", category: "governance",
    title: "C2PA Durable Credentials (NEW)",
    description: "C2PA 2.2 (May 2025) Durable Content Credentials — soft + hard binding (Digimarc-compatible). Survives compression, crop, screenshot, adversarial removal. First-mover before Adobe ships official tooling. 3 perceptual methods (Digimarc soft / robust pHash / video pdf-hash)." },
  { slug: "meok-eu-ai-act-art-26-fria-mcp", version: "1.0.0", category: "governance",
    title: "EU AI Act Article 26(9) FRIA (NEW)",
    description: "Auto-generates Fundamental Rights Impact Assessment per Article 27(1) 9 mandatory elements. Triggers for public bodies, private operators of public services, creditworthiness + life/health-insurance pricers. Cross-walks to EDPB DPIA template. £1,500/mo enterprise wedge (consultants charge £20K-£100K manually)." },
  { slug: "meok-eu-ai-act-art-13-ifu-mcp", version: "1.0.0", category: "governance",
    title: "EU AI Act Article 13 IFU (NEW)",
    description: "Provider-side Instructions for Use generator per Article 13(3) — 7 mandatory elements: identity + characteristics + pre-determined changes + Art 14 human oversight + compute lifecycle + log mechanisms + other-relevant. Crosswalks to deployer FRIA. Pairs with meok-eu-ai-act-art-26-fria-mcp." },
  { slug: "meok-eu-aia-art-9-rms-mcp", version: "1.0.0", category: "governance",
    title: "EU AI Act Article 9 RMS (NEW)",
    description: "Risk Management System generator per Article 9 — 4-step iteration (identify / estimate / post-market / mitigate) + 12 risk categories + signed Annex IV bundle. Completes the provider-side triple with Art 13 IFU + AI-BOM. Every high-risk AI provider needs an RMS before market placement." },
  { slug: "meok-w3c-tdm-rights-mcp", version: "1.0.0", category: "governance",
    title: "W3C TDM Rights (CDSM Art 4(3)) (NEW)",
    description: "EU CDSM Directive Article 4(3) Text + Data Mining opt-out. Issues + scans HTTP/HTML/robots.txt/C2PA reservation signals across 20+ AI agents (GPTBot/ClaudeBot/Google-Extended/etc.). Liability shield: signs each training-run scan with audit-defensible attestation. First-mover — nobody else has shipped this." },
  { slug: "dora-nis2-crosswalk-mcp", version: "1.0.2", category: "governance",
    title: "DORA × NIS2 Crosswalk",
    description: "Map DORA obligations to NIS2 Article 21-23 measures for dual-compliance scoring. EU banks, insurers, CASPs, CTPPs." },
  { slug: "bias-detection-mcp", version: "1.1.3", category: "governance",
    title: "Bias Detection",
    description: "Demographic analysis, fairness metrics, mitigation strategies, EU AI Act Article 10 compliance. Signed Article 10 certificates." },
  { slug: "watermarking-authenticity-mcp", version: "1.0.2", category: "governance",
    title: "Watermarking + C2PA Authenticity",
    description: "EU AI Act Article 50 watermarking. C2PA manifest generation, AI content detection, signed conformity attestations. Aug 2026 cliff." },
  { slug: "agent-content-watermark-mcp", version: "1.0.0", category: "governance",
    title: "Agent Content Watermark (NEW)",
    description: "Dedicated EU AI Act Article 50(2) GenAI watermarking MCP. Visible label + invisible payload + perceptual anchor per the GPAI Code of Practice. 5 modalities (image / text / audio / video / code). C2PA manifest envelope. 2 Aug 2026 cliff." },
  { slug: "meok-eu-aigc-icon-mcp", version: "1.0.0", category: "governance",
    title: "EU AIGC Icon (NEW)",
    description: "EU AI Act Code of Practice 2nd draft (Jan 2026) introduced the EU icon + label spec for AI-generated content. 8 emitters: C2PA 2.2 assertion · HTML meta + link tags · image ICC private tag · audio ID3v2 frames · video keyframe uuid box. First-mover — nobody else ships this." },
  { slug: "uk-ai-bill-compliance-mcp", version: "1.0.3", category: "governance",
    title: "UK AI Bill Compliance",
    description: "UK AI White Paper 5 principles, AI (Regulation) Bill audit, Algorithmic Transparency Recording Standard, ICO/FCA/MHRA/CMA/Ofcom/HSE guidance." },

  // ── A2A patterns (15) ──────────────────────────────────────────
  { slug: "bft-progress-council-mcp", version: "1.0.0", category: "a2a",
    title: "BFT Progress Council (NEW)",
    description: "5-voter Byzantine Fault Tolerant council halts agentic loops when 3-of-5 voters agree no real progress is happening. Detects: repetition · identical errors · goal drift · rapid-fire spinning · no artefact growth. The anti-loop guardrail every agent fleet needs. Saves £1-£3 per agent run on free tier; £100-£1,000/mo on Substrate." },
  { slug: "agent-token-budget-mcp", version: "1.0.0", category: "a2a",
    title: "Agent Token Budget (NEW)",
    description: "Hard per-session spend cap with signed budget-exhausted attestations. 13 pre-loaded model rates. Twin of BFT Progress Council — spend axis vs stall axis. Pays for itself first time it halts an over-spending agent." },
  { slug: "agent-cost-allocator-mcp", version: "1.0.0", category: "a2a",
    title: "Agent Cost Allocator (NEW)",
    description: "Multi-tenant LLM cost attribution for chargeback billing. Splits one agent's spend across many tenants with signed per-tenant chargeback summaries. Companion to agent-token-budget." },
  { slug: "agent-x402-paywall-mcp", version: "1.0.0", category: "a2a",
    title: "Agent x402 Paywall (NEW)",
    description: "Coinbase HTTP 402 + on-chain settlement. Agents pay per-call without a Stripe account. USDC on Base/Polygon/Solana + Lightning. Pure HTTP. The plumbing for the agent economy." },
  { slug: "agent-commerce-protocol-mcp", version: "1.0.0", category: "a2a",
    title: "Agent Commerce Protocol (Stripe ACP) (NEW)",
    description: "Bridges Stripe ACP + Google AP2 + Coinbase x402 — the only MCP that covers all 3 live agent-payment protocols. PSD2 + MiCA + 6AMLD + FinCEN BSA overlays. Explicitly addresses the IBM ACP / Stripe ACP name collision." },
  { slug: "oasf-agent-directory-mcp", version: "1.0.0", category: "a2a",
    title: "OASF Agent Directory (NEW)",
    description: "Bridges Cisco Outshift OASF + AGNTCY Directory under Linux Foundation. Converts MCP server.json and A2A agent-cards into OASF manifests so MEOK agents appear in the enterprise-procurement directory layer. OCI-based schema, capability taxonomy across 7 categories." },
  { slug: "eudi-wallet-mcp", version: "1.0.0", category: "a2a",
    title: "EUDI Wallet (NEW)",
    description: "EU Digital Identity Wallet bridge for AI agents (eIDAS 2.0). Covers ISO/IEC 18013-5 mDoc, W3C Verifiable Credentials 2.0, OID4VC + OID4VP, EUDI ARF v1.7. Selective disclosure (GDPR Art 5 minimisation). The wallet-based agent-identity bridge for 2026 EU deployments." },
  { slug: "agent-replay-debugger-mcp", version: "1.0.0", category: "a2a",
    title: "Agent Replay Debugger (NEW)",
    description: "Step-debugger for agentic loops. Records every action (input, output, model, tokens, ms, cost) so you can replay deterministically. Branch from any step. Search + export + HMAC-sign for audit. Pairs with BFT Progress Council + Audit Logger." },
  { slug: "meok-stripe-acp-checkout-mcp", version: "1.0.0", category: "a2a",
    title: "Stripe ACP Checkout (NEW)",
    description: "Stripe Agentic Commerce Protocol bridge — ChatGPT shopping checkout intents + AP2 mandate crosswalk + PSD2 SCA + signed receipts. 60+ ACP launch partners catalogued (Shopify / Etsy / Instacart / DoorDash / Uber Eats / Expedia / etc.)." },
  { slug: "meok-coinbase-x402-receipt-mcp", version: "1.0.0", category: "a2a",
    title: "Coinbase x402 Receipt (NEW)",
    description: "Signed on-chain settlement receipts for agentic payments. 7 chains (Base / Polygon / Solana / Lightning / Arbitrum / Optimism / Ethereum). MiCA Article 60 + 64 crosswalk. Stripe ACP intent linkage. Closes the agentic-payment chain — only thing that gives MiCA-defensible proof for x402 / on-chain settlements." },
  { slug: "meok-aaif-agent-card-mcp", version: "1.0.0", category: "a2a",
    title: "AAIF Agent Card (NEW)",
    description: "Linux Foundation AAIF agent identity bridge — publishes /.well-known/agent-card with DID + capabilities + endpoints + trust attestations. Bridges A2A and Cisco OASF manifests to AAIF. First-mover for the AAIF identity spec." },
  { slug: "meok-ap2-mandate-mcp", version: "1.0.0", category: "a2a",
    title: "Google AP2 Mandate (NEW)",
    description: "Google AP2 v0.2.0 — signed user-side spend mandate for agentic commerce. 7 scopes (merchant / category / subscription / negotiation / search / data / A2A). PSD2 SCA crosswalk (passkey strong, SMS weak, Art 13 low-value exemption). MiCA + 6AMLD overlays." },
  { slug: "meok-x402-wrap-mcp", version: "1.0.0", category: "a2a",
    title: "x402 Wrap (NEW)",
    description: "1-line USDC paywall for any FastMCP tool. One decorator turns any tool into a pay-per-call endpoint settled in USDC on Base / Polygon / Solana or BTC on Lightning. The minimal wrapper that Coinbase + Cloudflare + Vercel never shipped." },
  { slug: "agent-prompt-injection-firewall-mcp", version: "1.0.4", category: "a2a",
    title: "Prompt Injection Firewall",
    description: "The WAF for AI agents — scans prompts, RAG docs, tool args, A2A payloads for OWASP LLM01 prompt injection BEFORE they reach a downstream agent." },
  { slug: "agent-data-residency-mcp", version: "1.0.2", category: "a2a",
    title: "Agent Data Residency",
    description: "GDPR Chapter V transfer-basis runtime guard for A2A. Adequacy decisions, SCCs, BCRs, EU AI Act Article 10 data governance." },
  { slug: "agent-handoff-certified-mcp", version: "1.0.4", category: "a2a",
    title: "Certified Agent Handoff",
    description: "Verifiable agent-to-agent task handoff with signed provenance chain. Non-repudiable A2A delegation." },
  { slug: "agent-policy-enforcement-mcp", version: "1.0.3", category: "a2a",
    title: "Agent Policy Enforcement",
    description: "Per-agent-pair IAM for A2A. Define policies, gate every call via evaluate_call. EU AI Act Art 14 + ISO 42001 Annex A.7 evidence." },
  { slug: "agent-audit-logger-mcp", version: "1.0.4", category: "a2a",
    title: "Agent Audit Logger",
    description: "Hash-chained HMAC-signed audit log MCP for A2A calls. EU AI Act Art 12 + DORA Art 17 + ISO 42001 clause 9 auditor-ready evidence." },
  { slug: "agent-rate-limiter-mcp", version: "1.0.3", category: "a2a",
    title: "Agent Rate Limiter",
    description: "Fleet-wide shared rate limiter for A2A + multi-MCP deployments. Sliding window + concurrency grants + signed enforcement attestations." },
  { slug: "a2a-governance-bridge-mcp", version: "1.0.4", category: "a2a",
    title: "A2A Governance Bridge",
    description: "Connects A2A protocol traffic to governance/audit infrastructure. Bridges agent-to-agent calls into compliance evidence chains." },
  { slug: "agent-commerce-payments-mcp", version: "1.0.4", category: "a2a",
    title: "Agent Commerce + Payments",
    description: "Agent-to-agent payment rails with PSD2 + EU MiCA-compliant transfer attestation." },
  { slug: "agent-delegation-mcp", version: "1.0.4", category: "a2a",
    title: "Agent Delegation",
    description: "Capability-scoped delegation between agents. Time-bounded, audit-logged, revocable." },
  { slug: "agent-identity-trust-mcp", version: "1.0.4", category: "a2a",
    title: "Agent Identity + Trust",
    description: "Cryptographic agent identity with W3C DID + verifiable credentials. Trust scores per agent endpoint." },
  { slug: "agent-negotiation-mcp", version: "1.0.4", category: "a2a",
    title: "Agent Negotiation",
    description: "Auction + bidding protocol primitives for multi-agent coordination. Signed negotiation transcripts." },
  { slug: "agent-orchestrator-mcp", version: "1.0.3", category: "a2a",
    title: "Agent Orchestrator",
    description: "Workflow orchestration over A2A — sequence, branch, retry across heterogeneous agents." },

  // ── Platform (geospatial — new public MCP) ─────────────────────
  { slug: "gods-eye-geospatial-mcp", version: "1.0.0", category: "platform",
    title: "Gods Eye Geospatial",
    description: "Civilian open-source geospatial awareness — wraps ESA Copernicus Sentinel-1/2/3/5p + OpenStreetMap + Overture Maps + Ordnance Survey UK + INSPIRE EU + DEFRA behind one MCP. Care Membrane ethics gate refuses high-risk targeting/surveillance queries." },

  // ── Developer tooling ──────────────────────────────────────────
  { slug: "mcp-spec-compliance-mcp", version: "1.0.0", category: "devtool",
    title: "MCP Spec Compliance (NEW)",
    description: "Audits any MCP server.json against the official Model Context Protocol spec (2025-12-11). Linting for required fields, semver, slug pattern, recommended fields, naming conventions. HMAC-signed conformity reports — meta-viral for every MCP author." },
  { slug: "meok-mcp-hardening-mcp", version: "1.0.0", category: "devtool",
    title: "MCP Hardening — Security Red-Team (NEW)",
    description: "Automated security red-team for any MCP server. Maps OWASP LLM Top 10 (2025) + 5 MCP-specific risks (tool spoofing, privilege exposure, plain-HTTP resources, ungated destructive verbs) to a 0-100 hardening score with HMAC-signed reports. Every MCP author wants this before publishing — every consumer wants it before loading." },
  { slug: "meok-agents-md-lint-mcp", version: "1.0.0", category: "devtool",
    title: "AGENTS.md Linter (NEW)",
    description: "Validates the cross-vendor coding-agent spec (AGENTS.md — Cursor / Claude Code / Cline / Windsurf / Aider / OpenAI Codex, stewarded by AAIF). Required-section gate, security smells (hardcoded secrets / dangerous instructions), consistency with package.json + pyproject.toml + Makefile. Generates passing templates for 6 project types." },
  { slug: "agent-mcp-router-mcp", version: "1.0.0", category: "devtool",
    title: "Agent MCP Router (NEW)",
    description: "One MCP that routes to the whole MEOK fleet. Holds 62 MEOK MCPs (plus your own registered ones) behind a single namespaced endpoint — solves the Claude Code / Cursor tool-count ceiling. Bundle subsets by category, HMAC-sign multi-MCP call chains." },
  { slug: "meok-mcp-cardgen-mcp", version: "1.0.0", category: "devtool",
    title: "MCP Cardgen (NEW)",
    description: "Generate signed .well-known MCP server cards in all 3 SEP shapes (1649 + 1960 + 2127). Claude Desktop 2.1 + Cursor 2026.4 auto-discover MCPs via these. The gap is ~2,000 MCPs on the registry don't have cards. Drop into any static-file host." },

  // ── Cybersecurity (1, more coming) ─────────────────────────────
  { slug: "sbom-cyclonedx-mcp", version: "1.0.2", category: "cybersec",
    title: "SBOM CycloneDX + SPDX",
    description: "SBOM generation in CycloneDX 1.6 + SPDX 2.3. Required by EO 14028, NIS2, CRA. Signed attestations." },

  // ── Trade verticals (3) ────────────────────────────────────────
  { slug: "haulage-uk-compliance-mcp", version: "1.0.1", category: "trade",
    title: "UK Haulage Compliance",
    description: "UK Operator Licence, tachograph, drivers' hours, DVSA roadside checks for 3.5T+ goods vehicles." },
  { slug: "skip-hire-ai-mcp", version: "1.0.1", category: "trade",
    title: "Skip Hire AI",
    description: "UK Waste Carrier Registration, EA waste codes, hazardous waste consignment notes for skip hire + waste transport." },
  { slug: "construction-iso-19650-mcp", version: "1.0.1", category: "trade",
    title: "Construction ISO 19650",
    description: "ISO 19650 / UK BIM Level 2 compliance. EIR, BEP, MIDP, TIDP, CDE structure validation." },

  // ── Platform + Care (4) ────────────────────────────────────────
  { slug: "ai-gateway-mcp", version: "1.0.4", category: "platform",
    title: "AI Gateway",
    description: "Unified gateway for multi-LLM routing — Claude, GPT, Gemini, Llama, local — with cost + latency observability." },
  { slug: "ai-self-audit-mcp", version: "1.0.5", category: "platform",
    title: "AI Self-Audit",
    description: "Continuous internal compliance audit — reads policy + checks every agent action against rule set." },
  { slug: "ai-ops-mcp", version: "1.0.4", category: "platform",
    title: "AI Ops",
    description: "AI runtime observability — token usage, cost, latency, error rates, drift detection." },
  { slug: "care-membrane-mcp", version: "1.0.5", category: "platform",
    title: "Care Membrane",
    description: "6-dimension Noddings care score + sovereignty + dignity scoring on every response. Portable safety eval." },
  { slug: "canada-aida-ai-mcp", version: "1.0.5", category: "platform",
    title: "Canada AIDA Compliance",
    description: "Artificial Intelligence and Data Act (Canada) compliance audit + Annex disclosure tools." },

  // ── Developer tools (4) ────────────────────────────────────────
  { slug: "api-docs-generator-ai-mcp", version: "1.0.4", category: "devtool",
    title: "API Docs Generator",
    description: "OpenAPI 3.1 + AsyncAPI 3.0 spec → human-readable docs with example payloads." },
  { slug: "api-tester-ai-mcp", version: "1.0.4", category: "devtool",
    title: "API Tester",
    description: "Generate test suites for any OpenAPI spec — happy path + edge cases + load tests." },
  { slug: "changelog-ai-mcp", version: "1.0.4", category: "devtool",
    title: "Changelog AI",
    description: "Keep-a-Changelog generator from git history + PR descriptions. Semver-aware." },
  { slug: "ci-cd-generator-ai-mcp", version: "1.0.4", category: "devtool",
    title: "CI/CD Generator",
    description: "Generate GitHub Actions / GitLab CI / Jenkins pipelines from a project description." },
  { slug: "accessibility-ai-mcp", version: "1.0.4", category: "devtool",
    title: "Accessibility AI",
    description: "WCAG 2.2 AA audit + remediation suggestions for any web page or component." },
  { slug: "backup-ai-mcp", version: "1.0.4", category: "devtool",
    title: "Backup AI",
    description: "Backup policy + RPO/RTO calculator + restore-test scheduler." },
  { slug: "blockchain-ai-mcp", version: "1.0.4", category: "devtool",
    title: "Blockchain AI",
    description: "EVM contract analysis, gas optimisation, Solidity audit primitives." },
  { slug: "blockchain-verification-mcp", version: "1.0.4", category: "devtool",
    title: "Blockchain Verification",
    description: "Verify on-chain attestations, signatures, and proof-of-existence claims." },

  // ── Industry (8) ───────────────────────────────────────────────
  { slug: "agriculture-robotics-mcp", version: "1.0.4", category: "industry",
    title: "Agriculture Robotics",
    description: "Farm-robotics command + telemetry for spray, harvest, weed-control robots." },
  { slug: "airspace-monitor-mcp", version: "1.0.4", category: "industry",
    title: "Airspace Monitor",
    description: "ADS-B + Mode S aircraft tracking, NOTAM lookup, conflict detection." },
  { slug: "accounting-ai-mcp", version: "1.0.3", category: "industry",
    title: "Accounting AI",
    description: "Double-entry bookkeeping primitives, VAT/Sales tax computation, P&L generation." },
  { slug: "ad-copy-ai-mcp", version: "1.0.3", category: "industry",
    title: "Ad Copy AI",
    description: "Brand-voice-constrained ad copy generation for Google + Meta + LinkedIn." },
  { slug: "ascii-art-ai-mcp", version: "1.0.4", category: "industry",
    title: "ASCII Art AI",
    description: "Text-to-ASCII rendering for CLI banners, READMEs, retro art." },
  { slug: "budget-planner-ai-mcp", version: "1.0.4", category: "industry",
    title: "Budget Planner",
    description: "Household + small-business budgeting with category breakdowns and trend forecasting." },
  { slug: "calendar-ai-mcp", version: "1.0.4", category: "industry",
    title: "Calendar AI",
    description: "Smart scheduling across multiple calendars, conflict resolution, prep-time blocks." },
  { slug: "churn-predictor-ai-mcp", version: "1.0.4", category: "industry",
    title: "Churn Predictor",
    description: "SaaS churn prediction from usage + billing + support signals." },
];

export const CATEGORIES: { id: RegistryMCP["category"]; label: string; description: string }[] = [
  { id: "governance", label: "Governance & Compliance", description: "EU AI Act, DORA, NIS2, CRA, UK AI Bill — purpose-built MCPs for regulated AI deployments." },
  { id: "a2a", label: "Agent-to-Agent (A2A)", description: "Identity, trust, audit, rate-limiting, handoff, policy enforcement — the substrate for multi-agent systems." },
  { id: "platform", label: "Platform & Care", description: "AI gateway, ops, self-audit, and the Care Membrane safety scoring." },
  { id: "cybersec", label: "Cybersecurity", description: "SBOM, MITRE ATT&CK + ATLAS, Sigstore, SLSA — supply-chain integrity for AI." },
  { id: "trade", label: "Trade Verticals", description: "Haulage, skip hire, construction ISO 19650 — UK trade-specific compliance." },
  { id: "devtool", label: "Developer Tools", description: "API docs, testers, changelog automation, accessibility audits — the boring-but-essential layer." },
  { id: "industry", label: "Industry & Operations", description: "Sector-specific MCPs from agriculture to accounting." },
];
