-- MEOK AI LABS — Schema migration v4
-- Adds: care_signals, diary_entries, notifications tables
--
-- Run against your Neon database:
--   psql $DATABASE_URL -f src/lib/db/migrate-v4.sql
--
-- All operations are idempotent (IF NOT EXISTS).

-- ── 1. Care signals ──────────────────────────────────────────────────────────
-- Proactive messages queued by the companion system when the user shows
-- signs of stress, mood change, or disengagement (Maternal Covenant).

CREATE TABLE IF NOT EXISTS care_signals (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  signal_type   TEXT NOT NULL,          -- 'check_in' | 'encouragement' | 'boundary' | 'celebration'
  message       TEXT NOT NULL,
  priority      TEXT NOT NULL DEFAULT 'medium',  -- 'low' | 'medium' | 'high'
  deliver_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  friend_test   BOOLEAN NOT NULL DEFAULT FALSE,  -- "friend test" — would a good friend send this?
  delivered     BOOLEAN NOT NULL DEFAULT FALSE,
  delivered_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_care_signals_user_id
  ON care_signals (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_care_signals_pending
  ON care_signals (user_id, deliver_at)
  WHERE delivered = FALSE;

-- ── 2. Diary entries ─────────────────────────────────────────────────────────
-- Companion introspection log — generated after significant conversations.
-- Used to track relationship evolution and companion "growth".

CREATE TABLE IF NOT EXISTS diary_entries (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  companion_id  TEXT NOT NULL,
  entry_type    TEXT NOT NULL DEFAULT 'reflection',  -- 'reflection' | 'milestone' | 'care_action' | 'memory'
  content       TEXT NOT NULL,
  topics        TEXT[] DEFAULT '{}',
  mood          TEXT,                -- companion's detected mood at entry time
  bond_value    NUMERIC(4,3) DEFAULT 0.5,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_diary_entries_user_companion
  ON diary_entries (user_id, companion_id, created_at DESC);

-- ── 3. Notifications ─────────────────────────────────────────────────────────
-- In-app notification inbox. Generated by: guardian alerts, level-ups,
-- care signals delivered, system events, companion milestones.

CREATE TABLE IF NOT EXISTS notifications (
  id            TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type          TEXT NOT NULL,          -- 'care_signal' | 'guardian_alert' | 'level_up' | 'system' | 'milestone'
  title         TEXT NOT NULL,
  message       TEXT NOT NULL,
  read          BOOLEAN NOT NULL DEFAULT FALSE,
  read_at       TIMESTAMPTZ,
  metadata      JSONB DEFAULT '{}',    -- extra data (companion_id, level, etc.)
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id
  ON notifications (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_unread
  ON notifications (user_id, read, created_at DESC)
  WHERE read = FALSE;

-- ── 4. Referrals ─────────────────────────────────────────────────────────────
-- Tracks successful referral redemptions. Each row = one referred user.
-- The referral_code on users is derived deterministically from their user ID
-- (so no stored column needed for reading — only for fast lookup).

ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_code TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_referral_code ON users (referral_code) WHERE referral_code IS NOT NULL;

CREATE TABLE IF NOT EXISTS referrals (
  id                TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  referrer_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  referred_user_id  TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code              TEXT NOT NULL,
  bond_points_awarded INTEGER NOT NULL DEFAULT 0,
  trial_days_granted  INTEGER NOT NULL DEFAULT 0,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_referrals_referred_user
  ON referrals (referred_user_id);   -- each user can only be referred once

CREATE INDEX IF NOT EXISTS idx_referrals_referrer
  ON referrals (referrer_id, created_at DESC);

-- ── 5. Bond points column (used by addBondPoints) ────────────────────────────
ALTER TABLE users ADD COLUMN IF NOT EXISTS bond_points INTEGER NOT NULL DEFAULT 0;

-- ── 6. Documents ─────────────────────────────────────────────────────────────
-- User-authored documents with AI-assist. Replaces localStorage-only storage.

CREATE TABLE IF NOT EXISTS documents (
  id          TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title       TEXT NOT NULL DEFAULT 'Untitled',
  content     TEXT NOT NULL DEFAULT '',
  word_count  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_documents_user_id
  ON documents (user_id, updated_at DESC);

-- ── 7. Conversations ─────────────────────────────────────────────────────────
-- Replaces the in-memory Map in /api/user/conversations/route.ts.
-- Each conversation is a chat session between a user and a companion.

CREATE TABLE IF NOT EXISTS conversations (
  id            TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  companion_id  TEXT NOT NULL DEFAULT 'aria',
  title         TEXT NOT NULL DEFAULT 'New conversation',
  message_count INTEGER NOT NULL DEFAULT 0,
  last_message  TEXT,                -- preview of the last message
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_conversations_user_id
  ON conversations (user_id, updated_at DESC)
  WHERE deleted_at IS NULL;

-- ── 8. Gaming sessions ───────────────────────────────────────────────────────
-- User-logged gaming sessions. Cross-device sync replaces localStorage.

CREATE TABLE IF NOT EXISTS gaming_sessions (
  id               TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  user_id          TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  game             TEXT NOT NULL,
  duration_minutes INTEGER NOT NULL DEFAULT 60,
  notes            TEXT NOT NULL DEFAULT '',
  rating           INTEGER NOT NULL DEFAULT 3 CHECK (rating BETWEEN 1 AND 5),
  session_date     DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gaming_sessions_user_id
  ON gaming_sessions (user_id, session_date DESC);

-- ── 9. Verify ────────────────────────────────────────────────────────────────
SELECT
  (SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'care_signals')      AS care_signals_table,
  (SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'diary_entries')     AS diary_entries_table,
  (SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'notifications')     AS notifications_table,
  (SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'referrals')         AS referrals_table,
  (SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'conversations')     AS conversations_table,
  (SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'documents')         AS documents_table,
  (SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'gaming_sessions')   AS gaming_sessions_table;
