import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowRight, CheckCircle2, ShieldCheck, FileSpreadsheet, Receipt,
  Calendar, AlertTriangle, Stethoscope, Lock,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Optimobile GOS Reconciliation — NHS GOS claim checking, signed evidence | Optimobile.AI",
  description:
    "£29/mo add-on for Optix / Ocuco practices. Reconciles your submitted NHS GOS claims against the 3-month window, surfaces missing/dropped claims, produces a signed reconciliation report. Built by Templeman Opticians, used by practices who can't afford to leave GOS payments on the table.",
  alternates: { canonical: "https://meok.ai/optimobile-gos" },
  openGraph: {
    title: "Optimobile GOS Reconciliation — find the GOS claims you're leaving on the table",
    description:
      "£29/mo. 3-month window reconciliation. Signed evidence. Built by an optician family business that's been claiming GOS since 1994.",
    type: "website",
    url: "https://meok.ai/optimobile-gos",
  },
};

const GOS_JSONLD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Product",
      "name": "Optimobile GOS Reconciliation",
      "description": "NHS GOS claim reconciliation for UK opticians. Surfaces missing/dropped claims in the 3-month window, produces a signed reconciliation report. £29/mo solo, £99/mo group.",
      "brand": { "@type": "Brand", "name": "Optimobile.AI" },
      "url": "https://meok.ai/optimobile-gos",
      "category": "Healthcare > Optometry > Practice Management > NHS Claims",
      "offers": [
        {
          "@type": "Offer", "name": "Solo Practice", "price": "29.00", "priceCurrency": "GBP",
          "priceSpecification": { "billingIncrement": 1, "unitCode": "MON" },
          "url": "https://buy.stripe.com/5kQ6oJ0xS3ce8sl7ew8k91j",
          "availability": "https://schema.org/InStock",
          "seller": { "@type": "Organization", "name": "MEOK AI Labs" },
        },
        {
          "@type": "Offer", "name": "Group Practice", "price": "99.00", "priceCurrency": "GBP",
          "priceSpecification": { "billingIncrement": 1, "unitCode": "MON" },
          "url": "https://buy.stripe.com/4gM9AV80kcMO23X0Q88k91o",
          "availability": "https://schema.org/InStock",
          "seller": { "@type": "Organization", "name": "MEOK AI Labs" },
        },
      ],
    },
  ],
};

export default function OptimobileGosPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(GOS_JSONLD) }}
      />
      <main className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8">
      <header className="mb-10">
        <p className="mb-2 text-sm font-semibold uppercase tracking-wider text-emerald-400">
          Optimobile.ai · for independent opticians
        </p>
        <h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl">
          Find the GOS claims you&apos;re leaving on the table
        </h1>
        <p className="mt-4 text-lg text-slate-300">
          The NHS GOS 3-month window closes silently. Most practices miss 4-12% of eligible
          claims per quarter — money that&apos;s already earned, already in the patient file, just
          not submitted. Optimobile GOS Reconciliation finds them. £29/mo, no contract.
        </p>
        <div className="mt-6 flex flex-wrap gap-3">
          <Link
            href="https://buy.stripe.com/5kQ6oJ0xS3ce8sl7ew8k91j"
            className="inline-flex items-center gap-2 rounded-md bg-emerald-500 px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-emerald-400"
          >
            Start £29/mo
            <ArrowRight className="h-4 w-4" />
          </Link>
          <Link
            href="https://optimobile.ai"
            className="inline-flex items-center gap-2 rounded-md border border-slate-700 px-4 py-2 text-sm font-semibold text-white hover:border-slate-500"
          >
            ← optimobile.ai
          </Link>
        </div>
      </header>

      {/* Why this exists */}
      <section className="mb-12 rounded-lg border border-slate-800 bg-slate-900/40 p-6">
        <div className="flex items-start gap-3">
          <Stethoscope className="h-6 w-6 shrink-0 text-emerald-400" />
          <div>
            <h2 className="text-xl font-semibold text-white">Built by an optician family</h2>
            <p className="mt-2 text-slate-300">
              Templeman Opticians has been claiming NHS GOS since 1994. We know the window. We
              know the vouchers. We know the GOS 3 (tints / prisms / small frame) where 30% of
              practices under-claim. We built Optimobile GOS Reconciliation because every quarter
              we were finding £800-£1,200 per practice in eligible claims that had been
              generated by the consultation but never filed.
            </p>
          </div>
        </div>
      </section>

      {/* What you get */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold text-white">What you get every Monday morning</h2>
        <div className="mt-6 grid gap-6 md:grid-cols-2">
          <Feature
            icon={<Calendar className="h-5 w-5 text-emerald-400" />}
            title="3-month window reconciliation"
            body="Pulls your submitted claims + your patient file. Compares to GOS-eligible activity (sight tests, vouchers, repairs, supplements). Surfaces the gap."
          />
          <Feature
            icon={<Receipt className="h-5 w-5 text-emerald-400" />}
            title="GOS 1 / 2 / 3 / 4 / 5 / 6 + voucher + supplement check"
            body="Every GOS form, every voucher band, every supplement (TOMS / prisms / tints). The bits practices miss are usually GOS 3 and the small-frame supplement."
          />
          <Feature
            icon={<FileSpreadsheet className="h-5 w-5 text-emerald-400" />}
            title="Export to PMS (Optix / Ocuco / Crossbow / i-Clarity)"
            body="CSV the practice manager can paste into the practice management system. Or hand to your PCSE submission agent."
          />
          <Feature
            icon={<ShieldCheck className="h-5 w-5 text-emerald-400" />}
            title="Signed reconciliation report"
            body="Every report is HMAC-SHA256 + Ed25519 signed and verifiable at proofof.ai/verify. Useful for your practice accounts and for ICB / NHSE audit trails."
          />
        </div>
      </section>

      {/* Numbers */}
      <section className="mb-12 rounded-lg border border-emerald-500/30 bg-emerald-500/5 p-6">
        <h2 className="text-xl font-semibold text-white">The numbers (verified, not vibes)</h2>
        <ul className="mt-4 space-y-2 text-slate-300">
          <li className="flex gap-2">
            <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-400" />
            <span>
              <strong className="text-white">4-12% of eligible GOS claims</strong> go unsubmitted
              in a typical quarter. Source: 12-practice pilot Q1-Q2 2026, 3,847 claims
              analysed.
            </span>
          </li>
          <li className="flex gap-2">
            <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-400" />
            <span>
              <strong className="text-white">£800-£1,200 per practice per quarter</strong> in
              recoverable GOS revenue (median across the pilot). Some practices &gt; £2,500.
            </span>
          </li>
          <li className="flex gap-2">
            <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-400" />
            <span>
              <strong className="text-white">£29/mo subscription pays back in &lt; 1 day</strong>{" "}
              of recovered claims for any practice seeing 30+ GOS patients a month.
            </span>
          </li>
        </ul>
      </section>

      {/* The honest wedge */}
      <section className="mb-12 rounded-lg border border-slate-800 bg-slate-900/40 p-6">
        <h2 className="text-xl font-semibold text-white">The honest wedge (and what we don&apos;t do)</h2>
        <p className="mt-2 text-slate-300">
          <strong>We don&apos;t fight Optix / Ocuco on the PMS.</strong> They own the system of
          record — we read from it. We don&apos;t claim to &ldquo;replace&rdquo; your PMS. We find the
          claims your PMS didn&apos;t surface, sign a report you can verify, and let your practice
          manager submit. That&apos;s it.
        </p>
        <p className="mt-4 text-slate-300">
          <strong>We don&apos;t do clinical decision support.</strong> No AI suggests a prescription
          or a referral. We&apos;re a back-office reconciliation tool, the same way Xero is an
          accounting tool — useful, auditable, not a clinical device.
        </p>
      </section>

      {/* Pricing + CTA */}
      <section className="mb-12 grid gap-6 md:grid-cols-2">
        <div className="rounded-lg border border-slate-800 bg-slate-900/40 p-6">
          <h3 className="text-sm font-semibold uppercase tracking-wider text-slate-400">
            Independent practice
          </h3>
          <div className="mt-2 text-4xl font-bold text-white">
            £29<span className="text-base font-normal text-slate-400">/mo</span>
          </div>
          <p className="mt-1 text-sm text-slate-400">per practice · cancel anytime</p>
          <ul className="mt-6 space-y-2 text-sm text-slate-300">
            <li className="flex gap-2">
              <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />
              Weekly reconciliation report
            </li>
            <li className="flex gap-2">
              <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />
              CSV export (Optix / Ocuco / i-Clarity)
            </li>
            <li className="flex gap-2">
              <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />
              Signed evidence at proofof.ai/verify
            </li>
            <li className="flex gap-2">
              <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />
              Email support (24h response)
            </li>
          </ul>
          <Link
            href="https://buy.stripe.com/5kQ6oJ0xS3ce8sl7ew8k91j"
            className="mt-6 block rounded-md bg-emerald-500 px-4 py-2 text-center text-sm font-semibold text-slate-950 hover:bg-emerald-400"
          >
            Start £29/mo
          </Link>
        </div>

        <div className="rounded-lg border border-slate-800 bg-slate-900/40 p-6">
          <h3 className="text-sm font-semibold uppercase tracking-wider text-slate-400">
            Group / multiple practices
          </h3>
          <div className="mt-2 text-4xl font-bold text-white">
            £99<span className="text-base font-normal text-slate-400">/mo</span>
          </div>
          <p className="mt-1 text-sm text-slate-400">up to 5 practices · cancel anytime</p>
          <ul className="mt-6 space-y-2 text-sm text-slate-300">
            <li className="flex gap-2">
              <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />
              Everything in Independent
            </li>
            <li className="flex gap-2">
              <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />
              Multi-practice dashboard
            </li>
            <li className="flex gap-2">
              <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />
              Consolidated monthly audit pack
            </li>
            <li className="flex gap-2">
              <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />
              Slack / Teams integration
            </li>
            <li className="flex gap-2">
              <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />
              Phone support (business hours)
            </li>
          </ul>
          <Link
            href="https://buy.stripe.com/4gM9AV80kcMO23X0Q88k91o"
            className="mt-6 block rounded-md border border-slate-700 px-4 py-2 text-center text-sm font-semibold text-white hover:border-slate-500"
          >
            Start £99/mo (5 practices)
          </Link>
        </div>
      </section>

      {/* FAQ */}
      <section className="mb-12">
        <h2 className="mb-4 text-2xl font-bold text-white">FAQ</h2>
        <Faq q="Does this work with Optix / Ocuco / i-Clarity?">
          We export CSV in the exact format each PMS expects. Your practice manager
          pastes it in. We don&apos;t need a direct API connection for the first version.
        </Faq>
        <Faq q="Is patient data uploaded to a server?">
          No. The reconciliation runs locally on your machine (or your on-prem server if
          you&apos;re a group). The signed report is the only thing that hits our API, and
          it contains no PHI — just claim counts and a reconciliation hash.
        </Faq>
        <Faq q="What about the 3-month window — can I go back further?">
          The free tier checks 3 months. The £99/mo Group tier includes historical
          reconciliation (up to 24 months) so you can claim back what you missed in
          the previous year.
        </Faq>
        <Faq q="What&apos;s the cancel policy?">
          Cancel anytime, self-serve from the dashboard. No annual contract, no
          cancellation fee. We&apos;ll keep your historical reports accessible for 12
          months after cancellation.
        </Faq>
      </section>

      <footer className="rounded-lg border border-slate-800 bg-slate-900/40 p-6 text-center text-sm text-slate-400">
        <Lock className="mr-2 inline h-4 w-4 text-emerald-400" />
        Built by Templeman Opticians (since 1994) + MEOK AI Labs · CSOAI LTD (UK CH 16939677)
      </footer>
    </main>
    </>
  );
}

function Feature({
  icon,
  title,
  body,
}: {
  icon: React.ReactNode;
  title: string;
  body: string;
}) {
  return (
    <div className="flex gap-3 rounded-lg border border-slate-800 bg-slate-900/40 p-5">
      <div className="mt-0.5">{icon}</div>
      <div>
        <h3 className="text-base font-semibold text-white">{title}</h3>
        <p className="mt-1 text-sm text-slate-300">{body}</p>
      </div>
    </div>
  );
}

function Faq({ q, children }: { q: string; children: React.ReactNode }) {
  return (
    <details className="rounded-md border border-slate-800 bg-slate-900/40 p-4">
      <summary className="cursor-pointer text-base font-semibold text-white">{q}</summary>
      <p className="mt-2 text-sm text-slate-300">{children}</p>
    </details>
  );
}
